// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mrpc-mt4-error.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mrpc_2dmt4_2derror_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mrpc_2dmt4_2derror_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mrpc_2dmt4_2derror_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mrpc_2dmt4_2derror_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mrpc_2dmt4_2derror_2eproto;
namespace mt4_term_api {
class Error;
struct ErrorDefaultTypeInternal;
extern ErrorDefaultTypeInternal _Error_default_instance_;
class ErrorProperty;
struct ErrorPropertyDefaultTypeInternal;
extern ErrorPropertyDefaultTypeInternal _ErrorProperty_default_instance_;
class LogFileInfo;
struct LogFileInfoDefaultTypeInternal;
extern LogFileInfoDefaultTypeInternal _LogFileInfo_default_instance_;
}  // namespace mt4_term_api
PROTOBUF_NAMESPACE_OPEN
template<> ::mt4_term_api::Error* Arena::CreateMaybeMessage<::mt4_term_api::Error>(Arena*);
template<> ::mt4_term_api::ErrorProperty* Arena::CreateMaybeMessage<::mt4_term_api::ErrorProperty>(Arena*);
template<> ::mt4_term_api::LogFileInfo* Arena::CreateMaybeMessage<::mt4_term_api::LogFileInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mt4_term_api {

enum LogType : int {
  Global = 0,
  MQL5 = 1,
  MQL4 = 2,
  LogType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  LogType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool LogType_IsValid(int value);
constexpr LogType LogType_MIN = Global;
constexpr LogType LogType_MAX = MQL4;
constexpr int LogType_ARRAYSIZE = LogType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LogType_descriptor();
template<typename T>
inline const std::string& LogType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, LogType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function LogType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    LogType_descriptor(), enum_t_value);
}
inline bool LogType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LogType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LogType>(
    LogType_descriptor(), name, value);
}
enum ErrorType : int {
  UNDEFINED = 0,
  MRPC = 1,
  MRPC_VALIDATION = 2,
  MRPC_TIMEOUT = 3,
  TERMINAL_API_TIMEOUT = 4,
  TERMINAL_API_GET_PARAMS = 5,
  TERMINAL_API_SET_RESULT = 6,
  TERMINAL_API_UNEXPECTED = 7,
  MQL_EXECUTION = 8,
  MQL_CUSTOM_EXECUTION = 9,
  ErrorType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ErrorType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ErrorType_IsValid(int value);
constexpr ErrorType ErrorType_MIN = UNDEFINED;
constexpr ErrorType ErrorType_MAX = MQL_CUSTOM_EXECUTION;
constexpr int ErrorType_ARRAYSIZE = ErrorType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ErrorType_descriptor();
template<typename T>
inline const std::string& ErrorType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ErrorType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ErrorType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ErrorType_descriptor(), enum_t_value);
}
inline bool ErrorType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ErrorType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ErrorType>(
    ErrorType_descriptor(), name, value);
}
enum MqlErrorCode : int {
  ERR_NO_ERROR = 0,
  ERR_NO_RESULT = 1,
  ERR_COMMON_ERROR = 2,
  ERR_INVALID_TRADE_PARAMETERS = 3,
  ERR_SERVER_BUSY = 4,
  ERR_OLD_VERSION = 5,
  ERR_NO_CONNECTION = 6,
  ERR_NOT_ENOUGH_RIGHTS = 7,
  ERR_TOO_FREQUENT_REQUESTS = 8,
  ERR_MALFUNCTIONAL_TRADE = 9,
  ERR_ACCOUNT_DISABLED = 64,
  ERR_INVALID_ACCOUNT = 65,
  ERR_TRADE_TIMEOUT = 128,
  ERR_INVALID_PRICE = 129,
  ERR_INVALID_STOPS = 130,
  ERR_INVALID_TRADE_VOLUME = 131,
  ERR_MARKET_CLOSED = 132,
  ERR_TRADE_DISABLED = 133,
  ERR_NOT_ENOUGH_MONEY = 134,
  ERR_PRICE_CHANGED = 135,
  ERR_OFF_QUOTES = 136,
  ERR_BROKER_BUSY = 137,
  ERR_REQUOTE = 138,
  ERR_ORDER_LOCKED = 139,
  ERR_LONG_POSITIONS_ONLY_ALLOWED = 140,
  ERR_TOO_MANY_REQUESTS = 141,
  ERR_TRADE_MODIFY_DENIED = 145,
  ERR_TRADE_CONTEXT_BUSY = 146,
  ERR_TRADE_EXPIRATION_DENIED = 147,
  ERR_TRADE_TOO_MANY_ORDERS = 148,
  ERR_TRADE_HEDGE_PROHIBITED = 149,
  ERR_TRADE_PROHIBITED_BY_FIFO = 150,
  ERR_NO_MQLERROR = 4000,
  ERR_WRONG_FUNCTION_POINTER = 4001,
  ERR_ARRAY_INDEX_OUT_OF_RANGE = 4002,
  ERR_NO_MEMORY_FOR_CALL_STACK = 4003,
  ERR_RECURSIVE_STACK_OVERFLOW = 4004,
  ERR_NOT_ENOUGH_STACK_FOR_PARAM = 4005,
  ERR_NO_MEMORY_FOR_PARAM_STRING = 4006,
  ERR_NO_MEMORY_FOR_TEMP_STRING = 4007,
  ERR_NOT_INITIALIZED_STRING = 4008,
  ERR_NOT_INITIALIZED_ARRAYSTRING = 4009,
  ERR_NO_MEMORY_FOR_ARRAYSTRING = 4010,
  ERR_TOO_LONG_STRING = 4011,
  ERR_REMAINDER_FROM_ZERO_DIVIDE = 4012,
  ERR_ZERO_DIVIDE = 4013,
  ERR_UNKNOWN_COMMAND = 4014,
  ERR_WRONG_JUMP = 4015,
  ERR_NOT_INITIALIZED_ARRAY = 4016,
  ERR_DLL_CALLS_NOT_ALLOWED = 4017,
  ERR_CANNOT_LOAD_LIBRARY = 4018,
  ERR_CANNOT_CALL_FUNCTION = 4019,
  ERR_EXTERNAL_CALLS_NOT_ALLOWED = 4020,
  ERR_NO_MEMORY_FOR_RETURNED_STR = 4021,
  ERR_SYSTEM_BUSY = 4022,
  ERR_DLLFUNC_CRITICALERROR = 4023,
  ERR_INTERNAL_ERROR = 4024,
  ERR_OUT_OF_MEMORY = 4025,
  ERR_INVALID_POINTER = 4026,
  ERR_FORMAT_TOO_MANY_FORMATTERS = 4027,
  ERR_FORMAT_TOO_MANY_PARAMETERS = 4028,
  ERR_ARRAY_INVALID = 4029,
  ERR_CHART_NOREPLY = 4030,
  ERR_INVALID_FUNCTION_PARAMSCNT = 4050,
  ERR_INVALID_FUNCTION_PARAMVALUE = 4051,
  ERR_STRING_FUNCTION_INTERNAL = 4052,
  ERR_SOME_ARRAY_ERROR = 4053,
  ERR_INCORRECT_SERIESARRAY_USING = 4054,
  ERR_CUSTOM_INDICATOR_ERROR = 4055,
  ERR_INCOMPATIBLE_ARRAYS = 4056,
  ERR_GLOBAL_VARIABLES_PROCESSING = 4057,
  ERR_GLOBAL_VARIABLE_NOT_FOUND = 4058,
  ERR_FUNC_NOT_ALLOWED_IN_TESTING = 4059,
  ERR_FUNCTION_NOT_CONFIRMED = 4060,
  ERR_SEND_MAIL_ERROR = 4061,
  ERR_STRING_PARAMETER_EXPECTED = 4062,
  ERR_INTEGER_PARAMETER_EXPECTED = 4063,
  ERR_DOUBLE_PARAMETER_EXPECTED = 4064,
  ERR_ARRAY_AS_PARAMETER_EXPECTED = 4065,
  ERR_HISTORY_WILL_UPDATED = 4066,
  ERR_TRADE_ERROR = 4067,
  ERR_RESOURCE_NOT_FOUND = 4068,
  ERR_RESOURCE_NOT_SUPPORTED = 4069,
  ERR_RESOURCE_DUPLICATED = 4070,
  ERR_INDICATOR_CANNOT_INIT = 4071,
  ERR_INDICATOR_CANNOT_LOAD = 4072,
  ERR_NO_HISTORY_DATA = 4073,
  ERR_NO_MEMORY_FOR_HISTORY = 4074,
  ERR_NO_MEMORY_FOR_INDICATOR = 4075,
  ERR_END_OF_FILE = 4099,
  ERR_SOME_FILE_ERROR = 4100,
  ERR_WRONG_FILE_NAME = 4101,
  ERR_TOO_MANY_OPENED_FILES = 4102,
  ERR_CANNOT_OPEN_FILE = 4103,
  ERR_INCOMPATIBLE_FILEACCESS = 4104,
  ERR_NO_ORDER_SELECTED = 4105,
  ERR_UNKNOWN_SYMBOL = 4106,
  ERR_INVALID_PRICE_PARAM = 4107,
  ERR_INVALID_TICKET = 4108,
  ERR_TRADE_NOT_ALLOWED = 4109,
  ERR_LONGS_NOT_ALLOWED = 4110,
  ERR_SHORTS_NOT_ALLOWED = 4111,
  ERR_TRADE_EXPERT_DISABLED_BY_SERVER = 4112,
  ERR_OBJECT_ALREADY_EXISTS = 4200,
  ERR_UNKNOWN_OBJECT_PROPERTY = 4201,
  ERR_OBJECT_DOES_NOT_EXIST = 4202,
  ERR_UNKNOWN_OBJECT_TYPE = 4203,
  ERR_NO_OBJECT_NAME = 4204,
  ERR_OBJECT_COORDINATES_ERROR = 4205,
  ERR_NO_SPECIFIED_SUBWINDOW = 4206,
  ERR_SOME_OBJECT_ERROR = 4207,
  ERR_FILE_CANNOT_OPEN = 5004,
  MqlErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MqlErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MqlErrorCode_IsValid(int value);
constexpr MqlErrorCode MqlErrorCode_MIN = ERR_NO_ERROR;
constexpr MqlErrorCode MqlErrorCode_MAX = ERR_FILE_CANNOT_OPEN;
constexpr int MqlErrorCode_ARRAYSIZE = MqlErrorCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MqlErrorCode_descriptor();
template<typename T>
inline const std::string& MqlErrorCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MqlErrorCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MqlErrorCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MqlErrorCode_descriptor(), enum_t_value);
}
inline bool MqlErrorCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MqlErrorCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MqlErrorCode>(
    MqlErrorCode_descriptor(), name, value);
}
// ===================================================================

class Error final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mt4_term_api.Error) */ {
 public:
  inline Error() : Error(nullptr) {}
  ~Error() override;
  explicit PROTOBUF_CONSTEXPR Error(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Error(const Error& from);
  Error(Error&& from) noexcept
    : Error() {
    *this = ::std::move(from);
  }

  inline Error& operator=(const Error& from) {
    CopyFrom(from);
    return *this;
  }
  inline Error& operator=(Error&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Error& default_instance() {
    return *internal_default_instance();
  }
  static inline const Error* internal_default_instance() {
    return reinterpret_cast<const Error*>(
               &_Error_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Error& a, Error& b) {
    a.Swap(&b);
  }
  inline void Swap(Error* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Error* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Error* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Error>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Error& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Error& from) {
    Error::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Error* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt4_term_api.Error";
  }
  protected:
  explicit Error(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPropertiesFieldNumber = 13,
    kErrorCodeFieldNumber = 2,
    kErrorMessageFieldNumber = 3,
    kMqlErrorDescriptionFieldNumber = 6,
    kStackTraceFieldNumber = 10,
    kCommandTypeNameFieldNumber = 11,
    kTypeFieldNumber = 1,
    kMqlErrorCodeFieldNumber = 4,
    kCommandIdFieldNumber = 12,
    kMqlErrorIntCodeFieldNumber = 5,
  };
  // repeated .mt4_term_api.ErrorProperty properties = 13;
  int properties_size() const;
  private:
  int _internal_properties_size() const;
  public:
  void clear_properties();
  ::mt4_term_api::ErrorProperty* mutable_properties(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mt4_term_api::ErrorProperty >*
      mutable_properties();
  private:
  const ::mt4_term_api::ErrorProperty& _internal_properties(int index) const;
  ::mt4_term_api::ErrorProperty* _internal_add_properties();
  public:
  const ::mt4_term_api::ErrorProperty& properties(int index) const;
  ::mt4_term_api::ErrorProperty* add_properties();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mt4_term_api::ErrorProperty >&
      properties() const;

  // string error_code = 2;
  void clear_error_code();
  const std::string& error_code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_code();
  PROTOBUF_NODISCARD std::string* release_error_code();
  void set_allocated_error_code(std::string* error_code);
  private:
  const std::string& _internal_error_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_code(const std::string& value);
  std::string* _internal_mutable_error_code();
  public:

  // string error_message = 3;
  void clear_error_message();
  const std::string& error_message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // string mql_error_description = 6;
  void clear_mql_error_description();
  const std::string& mql_error_description() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_mql_error_description(ArgT0&& arg0, ArgT... args);
  std::string* mutable_mql_error_description();
  PROTOBUF_NODISCARD std::string* release_mql_error_description();
  void set_allocated_mql_error_description(std::string* mql_error_description);
  private:
  const std::string& _internal_mql_error_description() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_mql_error_description(const std::string& value);
  std::string* _internal_mutable_mql_error_description();
  public:

  // string stack_trace = 10;
  void clear_stack_trace();
  const std::string& stack_trace() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_stack_trace(ArgT0&& arg0, ArgT... args);
  std::string* mutable_stack_trace();
  PROTOBUF_NODISCARD std::string* release_stack_trace();
  void set_allocated_stack_trace(std::string* stack_trace);
  private:
  const std::string& _internal_stack_trace() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_stack_trace(const std::string& value);
  std::string* _internal_mutable_stack_trace();
  public:

  // string command_type_name = 11;
  void clear_command_type_name();
  const std::string& command_type_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_command_type_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_command_type_name();
  PROTOBUF_NODISCARD std::string* release_command_type_name();
  void set_allocated_command_type_name(std::string* command_type_name);
  private:
  const std::string& _internal_command_type_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_command_type_name(const std::string& value);
  std::string* _internal_mutable_command_type_name();
  public:

  // .mt4_term_api.ErrorType type = 1;
  void clear_type();
  ::mt4_term_api::ErrorType type() const;
  void set_type(::mt4_term_api::ErrorType value);
  private:
  ::mt4_term_api::ErrorType _internal_type() const;
  void _internal_set_type(::mt4_term_api::ErrorType value);
  public:

  // .mt4_term_api.MqlErrorCode mql_error_code = 4;
  void clear_mql_error_code();
  ::mt4_term_api::MqlErrorCode mql_error_code() const;
  void set_mql_error_code(::mt4_term_api::MqlErrorCode value);
  private:
  ::mt4_term_api::MqlErrorCode _internal_mql_error_code() const;
  void _internal_set_mql_error_code(::mt4_term_api::MqlErrorCode value);
  public:

  // int64 commandId = 12;
  void clear_commandid();
  int64_t commandid() const;
  void set_commandid(int64_t value);
  private:
  int64_t _internal_commandid() const;
  void _internal_set_commandid(int64_t value);
  public:

  // int32 mql_error_int_code = 5;
  void clear_mql_error_int_code();
  int32_t mql_error_int_code() const;
  void set_mql_error_int_code(int32_t value);
  private:
  int32_t _internal_mql_error_int_code() const;
  void _internal_set_mql_error_int_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:mt4_term_api.Error)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mt4_term_api::ErrorProperty > properties_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_code_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mql_error_description_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stack_trace_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr command_type_name_;
    int type_;
    int mql_error_code_;
    int64_t commandid_;
    int32_t mql_error_int_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mrpc_2dmt4_2derror_2eproto;
};
// -------------------------------------------------------------------

class ErrorProperty final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mt4_term_api.ErrorProperty) */ {
 public:
  inline ErrorProperty() : ErrorProperty(nullptr) {}
  ~ErrorProperty() override;
  explicit PROTOBUF_CONSTEXPR ErrorProperty(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ErrorProperty(const ErrorProperty& from);
  ErrorProperty(ErrorProperty&& from) noexcept
    : ErrorProperty() {
    *this = ::std::move(from);
  }

  inline ErrorProperty& operator=(const ErrorProperty& from) {
    CopyFrom(from);
    return *this;
  }
  inline ErrorProperty& operator=(ErrorProperty&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ErrorProperty& default_instance() {
    return *internal_default_instance();
  }
  static inline const ErrorProperty* internal_default_instance() {
    return reinterpret_cast<const ErrorProperty*>(
               &_ErrorProperty_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ErrorProperty& a, ErrorProperty& b) {
    a.Swap(&b);
  }
  inline void Swap(ErrorProperty* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ErrorProperty* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ErrorProperty* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ErrorProperty>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ErrorProperty& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ErrorProperty& from) {
    ErrorProperty::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ErrorProperty* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt4_term_api.ErrorProperty";
  }
  protected:
  explicit ErrorProperty(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorArgKeyFieldNumber = 1,
    kErrorArgValueFieldNumber = 2,
  };
  // string error_arg_key = 1;
  void clear_error_arg_key();
  const std::string& error_arg_key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_arg_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_arg_key();
  PROTOBUF_NODISCARD std::string* release_error_arg_key();
  void set_allocated_error_arg_key(std::string* error_arg_key);
  private:
  const std::string& _internal_error_arg_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_arg_key(const std::string& value);
  std::string* _internal_mutable_error_arg_key();
  public:

  // string error_arg_value = 2;
  void clear_error_arg_value();
  const std::string& error_arg_value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_arg_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_arg_value();
  PROTOBUF_NODISCARD std::string* release_error_arg_value();
  void set_allocated_error_arg_value(std::string* error_arg_value);
  private:
  const std::string& _internal_error_arg_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_arg_value(const std::string& value);
  std::string* _internal_mutable_error_arg_value();
  public:

  // @@protoc_insertion_point(class_scope:mt4_term_api.ErrorProperty)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_arg_key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_arg_value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mrpc_2dmt4_2derror_2eproto;
};
// -------------------------------------------------------------------

class LogFileInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mt4_term_api.LogFileInfo) */ {
 public:
  inline LogFileInfo() : LogFileInfo(nullptr) {}
  ~LogFileInfo() override;
  explicit PROTOBUF_CONSTEXPR LogFileInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogFileInfo(const LogFileInfo& from);
  LogFileInfo(LogFileInfo&& from) noexcept
    : LogFileInfo() {
    *this = ::std::move(from);
  }

  inline LogFileInfo& operator=(const LogFileInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogFileInfo& operator=(LogFileInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogFileInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogFileInfo* internal_default_instance() {
    return reinterpret_cast<const LogFileInfo*>(
               &_LogFileInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(LogFileInfo& a, LogFileInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(LogFileInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogFileInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogFileInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogFileInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LogFileInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LogFileInfo& from) {
    LogFileInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogFileInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt4_term_api.LogFileInfo";
  }
  protected:
  explicit LogFileInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFullPathFieldNumber = 2,
    kNameFieldNumber = 3,
    kContentFieldNumber = 4,
    kLogTypeFieldNumber = 1,
  };
  // string full_path = 2;
  void clear_full_path();
  const std::string& full_path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_full_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_full_path();
  PROTOBUF_NODISCARD std::string* release_full_path();
  void set_allocated_full_path(std::string* full_path);
  private:
  const std::string& _internal_full_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_full_path(const std::string& value);
  std::string* _internal_mutable_full_path();
  public:

  // string name = 3;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string content = 4;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // .mt4_term_api.LogType log_type = 1;
  void clear_log_type();
  ::mt4_term_api::LogType log_type() const;
  void set_log_type(::mt4_term_api::LogType value);
  private:
  ::mt4_term_api::LogType _internal_log_type() const;
  void _internal_set_log_type(::mt4_term_api::LogType value);
  public:

  // @@protoc_insertion_point(class_scope:mt4_term_api.LogFileInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr full_path_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
    int log_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mrpc_2dmt4_2derror_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Error

// .mt4_term_api.ErrorType type = 1;
inline void Error::clear_type() {
  _impl_.type_ = 0;
}
inline ::mt4_term_api::ErrorType Error::_internal_type() const {
  return static_cast< ::mt4_term_api::ErrorType >(_impl_.type_);
}
inline ::mt4_term_api::ErrorType Error::type() const {
  // @@protoc_insertion_point(field_get:mt4_term_api.Error.type)
  return _internal_type();
}
inline void Error::_internal_set_type(::mt4_term_api::ErrorType value) {
  
  _impl_.type_ = value;
}
inline void Error::set_type(::mt4_term_api::ErrorType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:mt4_term_api.Error.type)
}

// string error_code = 2;
inline void Error::clear_error_code() {
  _impl_.error_code_.ClearToEmpty();
}
inline const std::string& Error::error_code() const {
  // @@protoc_insertion_point(field_get:mt4_term_api.Error.error_code)
  return _internal_error_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Error::set_error_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mt4_term_api.Error.error_code)
}
inline std::string* Error::mutable_error_code() {
  std::string* _s = _internal_mutable_error_code();
  // @@protoc_insertion_point(field_mutable:mt4_term_api.Error.error_code)
  return _s;
}
inline const std::string& Error::_internal_error_code() const {
  return _impl_.error_code_.Get();
}
inline void Error::_internal_set_error_code(const std::string& value) {
  
  _impl_.error_code_.Set(value, GetArenaForAllocation());
}
inline std::string* Error::_internal_mutable_error_code() {
  
  return _impl_.error_code_.Mutable(GetArenaForAllocation());
}
inline std::string* Error::release_error_code() {
  // @@protoc_insertion_point(field_release:mt4_term_api.Error.error_code)
  return _impl_.error_code_.Release();
}
inline void Error::set_allocated_error_code(std::string* error_code) {
  if (error_code != nullptr) {
    
  } else {
    
  }
  _impl_.error_code_.SetAllocated(error_code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_code_.IsDefault()) {
    _impl_.error_code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mt4_term_api.Error.error_code)
}

// string error_message = 3;
inline void Error::clear_error_message() {
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& Error::error_message() const {
  // @@protoc_insertion_point(field_get:mt4_term_api.Error.error_message)
  return _internal_error_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Error::set_error_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mt4_term_api.Error.error_message)
}
inline std::string* Error::mutable_error_message() {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:mt4_term_api.Error.error_message)
  return _s;
}
inline const std::string& Error::_internal_error_message() const {
  return _impl_.error_message_.Get();
}
inline void Error::_internal_set_error_message(const std::string& value) {
  
  _impl_.error_message_.Set(value, GetArenaForAllocation());
}
inline std::string* Error::_internal_mutable_error_message() {
  
  return _impl_.error_message_.Mutable(GetArenaForAllocation());
}
inline std::string* Error::release_error_message() {
  // @@protoc_insertion_point(field_release:mt4_term_api.Error.error_message)
  return _impl_.error_message_.Release();
}
inline void Error::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  _impl_.error_message_.SetAllocated(error_message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mt4_term_api.Error.error_message)
}

// .mt4_term_api.MqlErrorCode mql_error_code = 4;
inline void Error::clear_mql_error_code() {
  _impl_.mql_error_code_ = 0;
}
inline ::mt4_term_api::MqlErrorCode Error::_internal_mql_error_code() const {
  return static_cast< ::mt4_term_api::MqlErrorCode >(_impl_.mql_error_code_);
}
inline ::mt4_term_api::MqlErrorCode Error::mql_error_code() const {
  // @@protoc_insertion_point(field_get:mt4_term_api.Error.mql_error_code)
  return _internal_mql_error_code();
}
inline void Error::_internal_set_mql_error_code(::mt4_term_api::MqlErrorCode value) {
  
  _impl_.mql_error_code_ = value;
}
inline void Error::set_mql_error_code(::mt4_term_api::MqlErrorCode value) {
  _internal_set_mql_error_code(value);
  // @@protoc_insertion_point(field_set:mt4_term_api.Error.mql_error_code)
}

// int32 mql_error_int_code = 5;
inline void Error::clear_mql_error_int_code() {
  _impl_.mql_error_int_code_ = 0;
}
inline int32_t Error::_internal_mql_error_int_code() const {
  return _impl_.mql_error_int_code_;
}
inline int32_t Error::mql_error_int_code() const {
  // @@protoc_insertion_point(field_get:mt4_term_api.Error.mql_error_int_code)
  return _internal_mql_error_int_code();
}
inline void Error::_internal_set_mql_error_int_code(int32_t value) {
  
  _impl_.mql_error_int_code_ = value;
}
inline void Error::set_mql_error_int_code(int32_t value) {
  _internal_set_mql_error_int_code(value);
  // @@protoc_insertion_point(field_set:mt4_term_api.Error.mql_error_int_code)
}

// string mql_error_description = 6;
inline void Error::clear_mql_error_description() {
  _impl_.mql_error_description_.ClearToEmpty();
}
inline const std::string& Error::mql_error_description() const {
  // @@protoc_insertion_point(field_get:mt4_term_api.Error.mql_error_description)
  return _internal_mql_error_description();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Error::set_mql_error_description(ArgT0&& arg0, ArgT... args) {
 
 _impl_.mql_error_description_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mt4_term_api.Error.mql_error_description)
}
inline std::string* Error::mutable_mql_error_description() {
  std::string* _s = _internal_mutable_mql_error_description();
  // @@protoc_insertion_point(field_mutable:mt4_term_api.Error.mql_error_description)
  return _s;
}
inline const std::string& Error::_internal_mql_error_description() const {
  return _impl_.mql_error_description_.Get();
}
inline void Error::_internal_set_mql_error_description(const std::string& value) {
  
  _impl_.mql_error_description_.Set(value, GetArenaForAllocation());
}
inline std::string* Error::_internal_mutable_mql_error_description() {
  
  return _impl_.mql_error_description_.Mutable(GetArenaForAllocation());
}
inline std::string* Error::release_mql_error_description() {
  // @@protoc_insertion_point(field_release:mt4_term_api.Error.mql_error_description)
  return _impl_.mql_error_description_.Release();
}
inline void Error::set_allocated_mql_error_description(std::string* mql_error_description) {
  if (mql_error_description != nullptr) {
    
  } else {
    
  }
  _impl_.mql_error_description_.SetAllocated(mql_error_description, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.mql_error_description_.IsDefault()) {
    _impl_.mql_error_description_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mt4_term_api.Error.mql_error_description)
}

// string stack_trace = 10;
inline void Error::clear_stack_trace() {
  _impl_.stack_trace_.ClearToEmpty();
}
inline const std::string& Error::stack_trace() const {
  // @@protoc_insertion_point(field_get:mt4_term_api.Error.stack_trace)
  return _internal_stack_trace();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Error::set_stack_trace(ArgT0&& arg0, ArgT... args) {
 
 _impl_.stack_trace_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mt4_term_api.Error.stack_trace)
}
inline std::string* Error::mutable_stack_trace() {
  std::string* _s = _internal_mutable_stack_trace();
  // @@protoc_insertion_point(field_mutable:mt4_term_api.Error.stack_trace)
  return _s;
}
inline const std::string& Error::_internal_stack_trace() const {
  return _impl_.stack_trace_.Get();
}
inline void Error::_internal_set_stack_trace(const std::string& value) {
  
  _impl_.stack_trace_.Set(value, GetArenaForAllocation());
}
inline std::string* Error::_internal_mutable_stack_trace() {
  
  return _impl_.stack_trace_.Mutable(GetArenaForAllocation());
}
inline std::string* Error::release_stack_trace() {
  // @@protoc_insertion_point(field_release:mt4_term_api.Error.stack_trace)
  return _impl_.stack_trace_.Release();
}
inline void Error::set_allocated_stack_trace(std::string* stack_trace) {
  if (stack_trace != nullptr) {
    
  } else {
    
  }
  _impl_.stack_trace_.SetAllocated(stack_trace, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.stack_trace_.IsDefault()) {
    _impl_.stack_trace_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mt4_term_api.Error.stack_trace)
}

// string command_type_name = 11;
inline void Error::clear_command_type_name() {
  _impl_.command_type_name_.ClearToEmpty();
}
inline const std::string& Error::command_type_name() const {
  // @@protoc_insertion_point(field_get:mt4_term_api.Error.command_type_name)
  return _internal_command_type_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Error::set_command_type_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.command_type_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mt4_term_api.Error.command_type_name)
}
inline std::string* Error::mutable_command_type_name() {
  std::string* _s = _internal_mutable_command_type_name();
  // @@protoc_insertion_point(field_mutable:mt4_term_api.Error.command_type_name)
  return _s;
}
inline const std::string& Error::_internal_command_type_name() const {
  return _impl_.command_type_name_.Get();
}
inline void Error::_internal_set_command_type_name(const std::string& value) {
  
  _impl_.command_type_name_.Set(value, GetArenaForAllocation());
}
inline std::string* Error::_internal_mutable_command_type_name() {
  
  return _impl_.command_type_name_.Mutable(GetArenaForAllocation());
}
inline std::string* Error::release_command_type_name() {
  // @@protoc_insertion_point(field_release:mt4_term_api.Error.command_type_name)
  return _impl_.command_type_name_.Release();
}
inline void Error::set_allocated_command_type_name(std::string* command_type_name) {
  if (command_type_name != nullptr) {
    
  } else {
    
  }
  _impl_.command_type_name_.SetAllocated(command_type_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.command_type_name_.IsDefault()) {
    _impl_.command_type_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mt4_term_api.Error.command_type_name)
}

// int64 commandId = 12;
inline void Error::clear_commandid() {
  _impl_.commandid_ = int64_t{0};
}
inline int64_t Error::_internal_commandid() const {
  return _impl_.commandid_;
}
inline int64_t Error::commandid() const {
  // @@protoc_insertion_point(field_get:mt4_term_api.Error.commandId)
  return _internal_commandid();
}
inline void Error::_internal_set_commandid(int64_t value) {
  
  _impl_.commandid_ = value;
}
inline void Error::set_commandid(int64_t value) {
  _internal_set_commandid(value);
  // @@protoc_insertion_point(field_set:mt4_term_api.Error.commandId)
}

// repeated .mt4_term_api.ErrorProperty properties = 13;
inline int Error::_internal_properties_size() const {
  return _impl_.properties_.size();
}
inline int Error::properties_size() const {
  return _internal_properties_size();
}
inline void Error::clear_properties() {
  _impl_.properties_.Clear();
}
inline ::mt4_term_api::ErrorProperty* Error::mutable_properties(int index) {
  // @@protoc_insertion_point(field_mutable:mt4_term_api.Error.properties)
  return _impl_.properties_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mt4_term_api::ErrorProperty >*
Error::mutable_properties() {
  // @@protoc_insertion_point(field_mutable_list:mt4_term_api.Error.properties)
  return &_impl_.properties_;
}
inline const ::mt4_term_api::ErrorProperty& Error::_internal_properties(int index) const {
  return _impl_.properties_.Get(index);
}
inline const ::mt4_term_api::ErrorProperty& Error::properties(int index) const {
  // @@protoc_insertion_point(field_get:mt4_term_api.Error.properties)
  return _internal_properties(index);
}
inline ::mt4_term_api::ErrorProperty* Error::_internal_add_properties() {
  return _impl_.properties_.Add();
}
inline ::mt4_term_api::ErrorProperty* Error::add_properties() {
  ::mt4_term_api::ErrorProperty* _add = _internal_add_properties();
  // @@protoc_insertion_point(field_add:mt4_term_api.Error.properties)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mt4_term_api::ErrorProperty >&
Error::properties() const {
  // @@protoc_insertion_point(field_list:mt4_term_api.Error.properties)
  return _impl_.properties_;
}

// -------------------------------------------------------------------

// ErrorProperty

// string error_arg_key = 1;
inline void ErrorProperty::clear_error_arg_key() {
  _impl_.error_arg_key_.ClearToEmpty();
}
inline const std::string& ErrorProperty::error_arg_key() const {
  // @@protoc_insertion_point(field_get:mt4_term_api.ErrorProperty.error_arg_key)
  return _internal_error_arg_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ErrorProperty::set_error_arg_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_arg_key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mt4_term_api.ErrorProperty.error_arg_key)
}
inline std::string* ErrorProperty::mutable_error_arg_key() {
  std::string* _s = _internal_mutable_error_arg_key();
  // @@protoc_insertion_point(field_mutable:mt4_term_api.ErrorProperty.error_arg_key)
  return _s;
}
inline const std::string& ErrorProperty::_internal_error_arg_key() const {
  return _impl_.error_arg_key_.Get();
}
inline void ErrorProperty::_internal_set_error_arg_key(const std::string& value) {
  
  _impl_.error_arg_key_.Set(value, GetArenaForAllocation());
}
inline std::string* ErrorProperty::_internal_mutable_error_arg_key() {
  
  return _impl_.error_arg_key_.Mutable(GetArenaForAllocation());
}
inline std::string* ErrorProperty::release_error_arg_key() {
  // @@protoc_insertion_point(field_release:mt4_term_api.ErrorProperty.error_arg_key)
  return _impl_.error_arg_key_.Release();
}
inline void ErrorProperty::set_allocated_error_arg_key(std::string* error_arg_key) {
  if (error_arg_key != nullptr) {
    
  } else {
    
  }
  _impl_.error_arg_key_.SetAllocated(error_arg_key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_arg_key_.IsDefault()) {
    _impl_.error_arg_key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mt4_term_api.ErrorProperty.error_arg_key)
}

// string error_arg_value = 2;
inline void ErrorProperty::clear_error_arg_value() {
  _impl_.error_arg_value_.ClearToEmpty();
}
inline const std::string& ErrorProperty::error_arg_value() const {
  // @@protoc_insertion_point(field_get:mt4_term_api.ErrorProperty.error_arg_value)
  return _internal_error_arg_value();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ErrorProperty::set_error_arg_value(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_arg_value_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mt4_term_api.ErrorProperty.error_arg_value)
}
inline std::string* ErrorProperty::mutable_error_arg_value() {
  std::string* _s = _internal_mutable_error_arg_value();
  // @@protoc_insertion_point(field_mutable:mt4_term_api.ErrorProperty.error_arg_value)
  return _s;
}
inline const std::string& ErrorProperty::_internal_error_arg_value() const {
  return _impl_.error_arg_value_.Get();
}
inline void ErrorProperty::_internal_set_error_arg_value(const std::string& value) {
  
  _impl_.error_arg_value_.Set(value, GetArenaForAllocation());
}
inline std::string* ErrorProperty::_internal_mutable_error_arg_value() {
  
  return _impl_.error_arg_value_.Mutable(GetArenaForAllocation());
}
inline std::string* ErrorProperty::release_error_arg_value() {
  // @@protoc_insertion_point(field_release:mt4_term_api.ErrorProperty.error_arg_value)
  return _impl_.error_arg_value_.Release();
}
inline void ErrorProperty::set_allocated_error_arg_value(std::string* error_arg_value) {
  if (error_arg_value != nullptr) {
    
  } else {
    
  }
  _impl_.error_arg_value_.SetAllocated(error_arg_value, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_arg_value_.IsDefault()) {
    _impl_.error_arg_value_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mt4_term_api.ErrorProperty.error_arg_value)
}

// -------------------------------------------------------------------

// LogFileInfo

// .mt4_term_api.LogType log_type = 1;
inline void LogFileInfo::clear_log_type() {
  _impl_.log_type_ = 0;
}
inline ::mt4_term_api::LogType LogFileInfo::_internal_log_type() const {
  return static_cast< ::mt4_term_api::LogType >(_impl_.log_type_);
}
inline ::mt4_term_api::LogType LogFileInfo::log_type() const {
  // @@protoc_insertion_point(field_get:mt4_term_api.LogFileInfo.log_type)
  return _internal_log_type();
}
inline void LogFileInfo::_internal_set_log_type(::mt4_term_api::LogType value) {
  
  _impl_.log_type_ = value;
}
inline void LogFileInfo::set_log_type(::mt4_term_api::LogType value) {
  _internal_set_log_type(value);
  // @@protoc_insertion_point(field_set:mt4_term_api.LogFileInfo.log_type)
}

// string full_path = 2;
inline void LogFileInfo::clear_full_path() {
  _impl_.full_path_.ClearToEmpty();
}
inline const std::string& LogFileInfo::full_path() const {
  // @@protoc_insertion_point(field_get:mt4_term_api.LogFileInfo.full_path)
  return _internal_full_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LogFileInfo::set_full_path(ArgT0&& arg0, ArgT... args) {
 
 _impl_.full_path_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mt4_term_api.LogFileInfo.full_path)
}
inline std::string* LogFileInfo::mutable_full_path() {
  std::string* _s = _internal_mutable_full_path();
  // @@protoc_insertion_point(field_mutable:mt4_term_api.LogFileInfo.full_path)
  return _s;
}
inline const std::string& LogFileInfo::_internal_full_path() const {
  return _impl_.full_path_.Get();
}
inline void LogFileInfo::_internal_set_full_path(const std::string& value) {
  
  _impl_.full_path_.Set(value, GetArenaForAllocation());
}
inline std::string* LogFileInfo::_internal_mutable_full_path() {
  
  return _impl_.full_path_.Mutable(GetArenaForAllocation());
}
inline std::string* LogFileInfo::release_full_path() {
  // @@protoc_insertion_point(field_release:mt4_term_api.LogFileInfo.full_path)
  return _impl_.full_path_.Release();
}
inline void LogFileInfo::set_allocated_full_path(std::string* full_path) {
  if (full_path != nullptr) {
    
  } else {
    
  }
  _impl_.full_path_.SetAllocated(full_path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.full_path_.IsDefault()) {
    _impl_.full_path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mt4_term_api.LogFileInfo.full_path)
}

// string name = 3;
inline void LogFileInfo::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& LogFileInfo::name() const {
  // @@protoc_insertion_point(field_get:mt4_term_api.LogFileInfo.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LogFileInfo::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mt4_term_api.LogFileInfo.name)
}
inline std::string* LogFileInfo::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:mt4_term_api.LogFileInfo.name)
  return _s;
}
inline const std::string& LogFileInfo::_internal_name() const {
  return _impl_.name_.Get();
}
inline void LogFileInfo::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* LogFileInfo::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* LogFileInfo::release_name() {
  // @@protoc_insertion_point(field_release:mt4_term_api.LogFileInfo.name)
  return _impl_.name_.Release();
}
inline void LogFileInfo::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mt4_term_api.LogFileInfo.name)
}

// string content = 4;
inline void LogFileInfo::clear_content() {
  _impl_.content_.ClearToEmpty();
}
inline const std::string& LogFileInfo::content() const {
  // @@protoc_insertion_point(field_get:mt4_term_api.LogFileInfo.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LogFileInfo::set_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.content_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mt4_term_api.LogFileInfo.content)
}
inline std::string* LogFileInfo::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:mt4_term_api.LogFileInfo.content)
  return _s;
}
inline const std::string& LogFileInfo::_internal_content() const {
  return _impl_.content_.Get();
}
inline void LogFileInfo::_internal_set_content(const std::string& value) {
  
  _impl_.content_.Set(value, GetArenaForAllocation());
}
inline std::string* LogFileInfo::_internal_mutable_content() {
  
  return _impl_.content_.Mutable(GetArenaForAllocation());
}
inline std::string* LogFileInfo::release_content() {
  // @@protoc_insertion_point(field_release:mt4_term_api.LogFileInfo.content)
  return _impl_.content_.Release();
}
inline void LogFileInfo::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  _impl_.content_.SetAllocated(content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mt4_term_api.LogFileInfo.content)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mt4_term_api

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::mt4_term_api::LogType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mt4_term_api::LogType>() {
  return ::mt4_term_api::LogType_descriptor();
}
template <> struct is_proto_enum< ::mt4_term_api::ErrorType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mt4_term_api::ErrorType>() {
  return ::mt4_term_api::ErrorType_descriptor();
}
template <> struct is_proto_enum< ::mt4_term_api::MqlErrorCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mt4_term_api::MqlErrorCode>() {
  return ::mt4_term_api::MqlErrorCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mrpc_2dmt4_2derror_2eproto
