// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mrpc-mt4-error.proto

#include "mrpc-mt4-error.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace mt4_term_api {
PROTOBUF_CONSTEXPR Error::Error(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.properties_)*/{}
  , /*decltype(_impl_.error_code_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.error_message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.mql_error_description_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.stack_trace_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.command_type_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.mql_error_code_)*/0
  , /*decltype(_impl_.commandid_)*/int64_t{0}
  , /*decltype(_impl_.mql_error_int_code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ErrorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ErrorDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ErrorDefaultTypeInternal() {}
  union {
    Error _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ErrorDefaultTypeInternal _Error_default_instance_;
PROTOBUF_CONSTEXPR ErrorProperty::ErrorProperty(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_arg_key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.error_arg_value_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ErrorPropertyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ErrorPropertyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ErrorPropertyDefaultTypeInternal() {}
  union {
    ErrorProperty _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ErrorPropertyDefaultTypeInternal _ErrorProperty_default_instance_;
PROTOBUF_CONSTEXPR LogFileInfo::LogFileInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.full_path_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.content_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.log_type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LogFileInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LogFileInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LogFileInfoDefaultTypeInternal() {}
  union {
    LogFileInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LogFileInfoDefaultTypeInternal _LogFileInfo_default_instance_;
}  // namespace mt4_term_api
static ::_pb::Metadata file_level_metadata_mrpc_2dmt4_2derror_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_mrpc_2dmt4_2derror_2eproto[3];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_mrpc_2dmt4_2derror_2eproto = nullptr;

const uint32_t TableStruct_mrpc_2dmt4_2derror_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::Error, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::Error, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::Error, _impl_.error_code_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::Error, _impl_.error_message_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::Error, _impl_.mql_error_code_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::Error, _impl_.mql_error_int_code_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::Error, _impl_.mql_error_description_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::Error, _impl_.stack_trace_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::Error, _impl_.command_type_name_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::Error, _impl_.commandid_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::Error, _impl_.properties_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::ErrorProperty, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::ErrorProperty, _impl_.error_arg_key_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::ErrorProperty, _impl_.error_arg_value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::LogFileInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::LogFileInfo, _impl_.log_type_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::LogFileInfo, _impl_.full_path_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::LogFileInfo, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::LogFileInfo, _impl_.content_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::mt4_term_api::Error)},
  { 16, -1, -1, sizeof(::mt4_term_api::ErrorProperty)},
  { 24, -1, -1, sizeof(::mt4_term_api::LogFileInfo)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::mt4_term_api::_Error_default_instance_._instance,
  &::mt4_term_api::_ErrorProperty_default_instance_._instance,
  &::mt4_term_api::_LogFileInfo_default_instance_._instance,
};

const char descriptor_table_protodef_mrpc_2dmt4_2derror_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024mrpc-mt4-error.proto\022\014mt4_term_api\"\274\002\n"
  "\005Error\022%\n\004type\030\001 \001(\0162\027.mt4_term_api.Erro"
  "rType\022\022\n\nerror_code\030\002 \001(\t\022\025\n\rerror_messa"
  "ge\030\003 \001(\t\0222\n\016mql_error_code\030\004 \001(\0162\032.mt4_t"
  "erm_api.MqlErrorCode\022\032\n\022mql_error_int_co"
  "de\030\005 \001(\005\022\035\n\025mql_error_description\030\006 \001(\t\022"
  "\023\n\013stack_trace\030\n \001(\t\022\031\n\021command_type_nam"
  "e\030\013 \001(\t\022\021\n\tcommandId\030\014 \001(\003\022/\n\nproperties"
  "\030\r \003(\0132\033.mt4_term_api.ErrorProperty\"\?\n\rE"
  "rrorProperty\022\025\n\rerror_arg_key\030\001 \001(\t\022\027\n\017e"
  "rror_arg_value\030\002 \001(\t\"h\n\013LogFileInfo\022\'\n\010l"
  "og_type\030\001 \001(\0162\025.mt4_term_api.LogType\022\021\n\t"
  "full_path\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\017\n\007content"
  "\030\004 \001(\t*)\n\007LogType\022\n\n\006Global\020\000\022\010\n\004MQL5\020\001\022"
  "\010\n\004MQL4\020\002*\351\001\n\tErrorType\022\r\n\tUNDEFINED\020\000\022\010"
  "\n\004MRPC\020\001\022\023\n\017MRPC_VALIDATION\020\002\022\020\n\014MRPC_TI"
  "MEOUT\020\003\022\030\n\024TERMINAL_API_TIMEOUT\020\004\022\033\n\027TER"
  "MINAL_API_GET_PARAMS\020\005\022\033\n\027TERMINAL_API_S"
  "ET_RESULT\020\006\022\033\n\027TERMINAL_API_UNEXPECTED\020\007"
  "\022\021\n\rMQL_EXECUTION\020\010\022\030\n\024MQL_CUSTOM_EXECUT"
  "ION\020\t*\226\032\n\014MqlErrorCode\022\020\n\014ERR_NO_ERROR\020\000"
  "\022\021\n\rERR_NO_RESULT\020\001\022\024\n\020ERR_COMMON_ERROR\020"
  "\002\022 \n\034ERR_INVALID_TRADE_PARAMETERS\020\003\022\023\n\017E"
  "RR_SERVER_BUSY\020\004\022\023\n\017ERR_OLD_VERSION\020\005\022\025\n"
  "\021ERR_NO_CONNECTION\020\006\022\031\n\025ERR_NOT_ENOUGH_R"
  "IGHTS\020\007\022\035\n\031ERR_TOO_FREQUENT_REQUESTS\020\010\022\033"
  "\n\027ERR_MALFUNCTIONAL_TRADE\020\t\022\030\n\024ERR_ACCOU"
  "NT_DISABLED\020@\022\027\n\023ERR_INVALID_ACCOUNT\020A\022\026"
  "\n\021ERR_TRADE_TIMEOUT\020\200\001\022\026\n\021ERR_INVALID_PR"
  "ICE\020\201\001\022\026\n\021ERR_INVALID_STOPS\020\202\001\022\035\n\030ERR_IN"
  "VALID_TRADE_VOLUME\020\203\001\022\026\n\021ERR_MARKET_CLOS"
  "ED\020\204\001\022\027\n\022ERR_TRADE_DISABLED\020\205\001\022\031\n\024ERR_NO"
  "T_ENOUGH_MONEY\020\206\001\022\026\n\021ERR_PRICE_CHANGED\020\207"
  "\001\022\023\n\016ERR_OFF_QUOTES\020\210\001\022\024\n\017ERR_BROKER_BUS"
  "Y\020\211\001\022\020\n\013ERR_REQUOTE\020\212\001\022\025\n\020ERR_ORDER_LOCK"
  "ED\020\213\001\022$\n\037ERR_LONG_POSITIONS_ONLY_ALLOWED"
  "\020\214\001\022\032\n\025ERR_TOO_MANY_REQUESTS\020\215\001\022\034\n\027ERR_T"
  "RADE_MODIFY_DENIED\020\221\001\022\033\n\026ERR_TRADE_CONTE"
  "XT_BUSY\020\222\001\022 \n\033ERR_TRADE_EXPIRATION_DENIE"
  "D\020\223\001\022\036\n\031ERR_TRADE_TOO_MANY_ORDERS\020\224\001\022\037\n\032"
  "ERR_TRADE_HEDGE_PROHIBITED\020\225\001\022!\n\034ERR_TRA"
  "DE_PROHIBITED_BY_FIFO\020\226\001\022\024\n\017ERR_NO_MQLER"
  "ROR\020\240\037\022\037\n\032ERR_WRONG_FUNCTION_POINTER\020\241\037\022"
  "!\n\034ERR_ARRAY_INDEX_OUT_OF_RANGE\020\242\037\022!\n\034ER"
  "R_NO_MEMORY_FOR_CALL_STACK\020\243\037\022!\n\034ERR_REC"
  "URSIVE_STACK_OVERFLOW\020\244\037\022#\n\036ERR_NOT_ENOU"
  "GH_STACK_FOR_PARAM\020\245\037\022#\n\036ERR_NO_MEMORY_F"
  "OR_PARAM_STRING\020\246\037\022\"\n\035ERR_NO_MEMORY_FOR_"
  "TEMP_STRING\020\247\037\022\037\n\032ERR_NOT_INITIALIZED_ST"
  "RING\020\250\037\022$\n\037ERR_NOT_INITIALIZED_ARRAYSTRI"
  "NG\020\251\037\022\"\n\035ERR_NO_MEMORY_FOR_ARRAYSTRING\020\252"
  "\037\022\030\n\023ERR_TOO_LONG_STRING\020\253\037\022#\n\036ERR_REMAI"
  "NDER_FROM_ZERO_DIVIDE\020\254\037\022\024\n\017ERR_ZERO_DIV"
  "IDE\020\255\037\022\030\n\023ERR_UNKNOWN_COMMAND\020\256\037\022\023\n\016ERR_"
  "WRONG_JUMP\020\257\037\022\036\n\031ERR_NOT_INITIALIZED_ARR"
  "AY\020\260\037\022\036\n\031ERR_DLL_CALLS_NOT_ALLOWED\020\261\037\022\034\n"
  "\027ERR_CANNOT_LOAD_LIBRARY\020\262\037\022\035\n\030ERR_CANNO"
  "T_CALL_FUNCTION\020\263\037\022#\n\036ERR_EXTERNAL_CALLS"
  "_NOT_ALLOWED\020\264\037\022#\n\036ERR_NO_MEMORY_FOR_RET"
  "URNED_STR\020\265\037\022\024\n\017ERR_SYSTEM_BUSY\020\266\037\022\036\n\031ER"
  "R_DLLFUNC_CRITICALERROR\020\267\037\022\027\n\022ERR_INTERN"
  "AL_ERROR\020\270\037\022\026\n\021ERR_OUT_OF_MEMORY\020\271\037\022\030\n\023E"
  "RR_INVALID_POINTER\020\272\037\022#\n\036ERR_FORMAT_TOO_"
  "MANY_FORMATTERS\020\273\037\022#\n\036ERR_FORMAT_TOO_MAN"
  "Y_PARAMETERS\020\274\037\022\026\n\021ERR_ARRAY_INVALID\020\275\037\022"
  "\026\n\021ERR_CHART_NOREPLY\020\276\037\022#\n\036ERR_INVALID_F"
  "UNCTION_PARAMSCNT\020\322\037\022$\n\037ERR_INVALID_FUNC"
  "TION_PARAMVALUE\020\323\037\022!\n\034ERR_STRING_FUNCTIO"
  "N_INTERNAL\020\324\037\022\031\n\024ERR_SOME_ARRAY_ERROR\020\325\037"
  "\022$\n\037ERR_INCORRECT_SERIESARRAY_USING\020\326\037\022\037"
  "\n\032ERR_CUSTOM_INDICATOR_ERROR\020\327\037\022\034\n\027ERR_I"
  "NCOMPATIBLE_ARRAYS\020\330\037\022$\n\037ERR_GLOBAL_VARI"
  "ABLES_PROCESSING\020\331\037\022\"\n\035ERR_GLOBAL_VARIAB"
  "LE_NOT_FOUND\020\332\037\022$\n\037ERR_FUNC_NOT_ALLOWED_"
  "IN_TESTING\020\333\037\022\037\n\032ERR_FUNCTION_NOT_CONFIR"
  "MED\020\334\037\022\030\n\023ERR_SEND_MAIL_ERROR\020\335\037\022\"\n\035ERR_"
  "STRING_PARAMETER_EXPECTED\020\336\037\022#\n\036ERR_INTE"
  "GER_PARAMETER_EXPECTED\020\337\037\022\"\n\035ERR_DOUBLE_"
  "PARAMETER_EXPECTED\020\340\037\022$\n\037ERR_ARRAY_AS_PA"
  "RAMETER_EXPECTED\020\341\037\022\035\n\030ERR_HISTORY_WILL_"
  "UPDATED\020\342\037\022\024\n\017ERR_TRADE_ERROR\020\343\037\022\033\n\026ERR_"
  "RESOURCE_NOT_FOUND\020\344\037\022\037\n\032ERR_RESOURCE_NO"
  "T_SUPPORTED\020\345\037\022\034\n\027ERR_RESOURCE_DUPLICATE"
  "D\020\346\037\022\036\n\031ERR_INDICATOR_CANNOT_INIT\020\347\037\022\036\n\031"
  "ERR_INDICATOR_CANNOT_LOAD\020\350\037\022\030\n\023ERR_NO_H"
  "ISTORY_DATA\020\351\037\022\036\n\031ERR_NO_MEMORY_FOR_HIST"
  "ORY\020\352\037\022 \n\033ERR_NO_MEMORY_FOR_INDICATOR\020\353\037"
  "\022\024\n\017ERR_END_OF_FILE\020\203 \022\030\n\023ERR_SOME_FILE_"
  "ERROR\020\204 \022\030\n\023ERR_WRONG_FILE_NAME\020\205 \022\036\n\031ER"
  "R_TOO_MANY_OPENED_FILES\020\206 \022\031\n\024ERR_CANNOT"
  "_OPEN_FILE\020\207 \022 \n\033ERR_INCOMPATIBLE_FILEAC"
  "CESS\020\210 \022\032\n\025ERR_NO_ORDER_SELECTED\020\211 \022\027\n\022E"
  "RR_UNKNOWN_SYMBOL\020\212 \022\034\n\027ERR_INVALID_PRIC"
  "E_PARAM\020\213 \022\027\n\022ERR_INVALID_TICKET\020\214 \022\032\n\025E"
  "RR_TRADE_NOT_ALLOWED\020\215 \022\032\n\025ERR_LONGS_NOT"
  "_ALLOWED\020\216 \022\033\n\026ERR_SHORTS_NOT_ALLOWED\020\217 "
  "\022(\n#ERR_TRADE_EXPERT_DISABLED_BY_SERVER\020"
  "\220 \022\036\n\031ERR_OBJECT_ALREADY_EXISTS\020\350 \022 \n\033ER"
  "R_UNKNOWN_OBJECT_PROPERTY\020\351 \022\036\n\031ERR_OBJE"
  "CT_DOES_NOT_EXIST\020\352 \022\034\n\027ERR_UNKNOWN_OBJE"
  "CT_TYPE\020\353 \022\027\n\022ERR_NO_OBJECT_NAME\020\354 \022!\n\034E"
  "RR_OBJECT_COORDINATES_ERROR\020\355 \022\037\n\032ERR_NO"
  "_SPECIFIED_SUBWINDOW\020\356 \022\032\n\025ERR_SOME_OBJE"
  "CT_ERROR\020\357 \022\031\n\024ERR_FILE_CANNOT_OPEN\020\214\'B3"
  "Z1git.mtapi.io/root/mrpc-proto.git/mt4/l"
  "ibraries/gob\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_mrpc_2dmt4_2derror_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_mrpc_2dmt4_2derror_2eproto = {
    false, false, 4219, descriptor_table_protodef_mrpc_2dmt4_2derror_2eproto,
    "mrpc-mt4-error.proto",
    &descriptor_table_mrpc_2dmt4_2derror_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_mrpc_2dmt4_2derror_2eproto::offsets,
    file_level_metadata_mrpc_2dmt4_2derror_2eproto, file_level_enum_descriptors_mrpc_2dmt4_2derror_2eproto,
    file_level_service_descriptors_mrpc_2dmt4_2derror_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_mrpc_2dmt4_2derror_2eproto_getter() {
  return &descriptor_table_mrpc_2dmt4_2derror_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_mrpc_2dmt4_2derror_2eproto(&descriptor_table_mrpc_2dmt4_2derror_2eproto);
namespace mt4_term_api {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LogType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_mrpc_2dmt4_2derror_2eproto);
  return file_level_enum_descriptors_mrpc_2dmt4_2derror_2eproto[0];
}
bool LogType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ErrorType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_mrpc_2dmt4_2derror_2eproto);
  return file_level_enum_descriptors_mrpc_2dmt4_2derror_2eproto[1];
}
bool ErrorType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MqlErrorCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_mrpc_2dmt4_2derror_2eproto);
  return file_level_enum_descriptors_mrpc_2dmt4_2derror_2eproto[2];
}
bool MqlErrorCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 64:
    case 65:
    case 128:
    case 129:
    case 130:
    case 131:
    case 132:
    case 133:
    case 134:
    case 135:
    case 136:
    case 137:
    case 138:
    case 139:
    case 140:
    case 141:
    case 145:
    case 146:
    case 147:
    case 148:
    case 149:
    case 150:
    case 4000:
    case 4001:
    case 4002:
    case 4003:
    case 4004:
    case 4005:
    case 4006:
    case 4007:
    case 4008:
    case 4009:
    case 4010:
    case 4011:
    case 4012:
    case 4013:
    case 4014:
    case 4015:
    case 4016:
    case 4017:
    case 4018:
    case 4019:
    case 4020:
    case 4021:
    case 4022:
    case 4023:
    case 4024:
    case 4025:
    case 4026:
    case 4027:
    case 4028:
    case 4029:
    case 4030:
    case 4050:
    case 4051:
    case 4052:
    case 4053:
    case 4054:
    case 4055:
    case 4056:
    case 4057:
    case 4058:
    case 4059:
    case 4060:
    case 4061:
    case 4062:
    case 4063:
    case 4064:
    case 4065:
    case 4066:
    case 4067:
    case 4068:
    case 4069:
    case 4070:
    case 4071:
    case 4072:
    case 4073:
    case 4074:
    case 4075:
    case 4099:
    case 4100:
    case 4101:
    case 4102:
    case 4103:
    case 4104:
    case 4105:
    case 4106:
    case 4107:
    case 4108:
    case 4109:
    case 4110:
    case 4111:
    case 4112:
    case 4200:
    case 4201:
    case 4202:
    case 4203:
    case 4204:
    case 4205:
    case 4206:
    case 4207:
    case 5004:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class Error::_Internal {
 public:
};

Error::Error(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mt4_term_api.Error)
}
Error::Error(const Error& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Error* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.properties_){from._impl_.properties_}
    , decltype(_impl_.error_code_){}
    , decltype(_impl_.error_message_){}
    , decltype(_impl_.mql_error_description_){}
    , decltype(_impl_.stack_trace_){}
    , decltype(_impl_.command_type_name_){}
    , decltype(_impl_.type_){}
    , decltype(_impl_.mql_error_code_){}
    , decltype(_impl_.commandid_){}
    , decltype(_impl_.mql_error_int_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_code().empty()) {
    _this->_impl_.error_code_.Set(from._internal_error_code(), 
      _this->GetArenaForAllocation());
  }
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_message().empty()) {
    _this->_impl_.error_message_.Set(from._internal_error_message(), 
      _this->GetArenaForAllocation());
  }
  _impl_.mql_error_description_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.mql_error_description_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_mql_error_description().empty()) {
    _this->_impl_.mql_error_description_.Set(from._internal_mql_error_description(), 
      _this->GetArenaForAllocation());
  }
  _impl_.stack_trace_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.stack_trace_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_stack_trace().empty()) {
    _this->_impl_.stack_trace_.Set(from._internal_stack_trace(), 
      _this->GetArenaForAllocation());
  }
  _impl_.command_type_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.command_type_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_command_type_name().empty()) {
    _this->_impl_.command_type_name_.Set(from._internal_command_type_name(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.type_, &from._impl_.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.mql_error_int_code_) -
    reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.mql_error_int_code_));
  // @@protoc_insertion_point(copy_constructor:mt4_term_api.Error)
}

inline void Error::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.properties_){arena}
    , decltype(_impl_.error_code_){}
    , decltype(_impl_.error_message_){}
    , decltype(_impl_.mql_error_description_){}
    , decltype(_impl_.stack_trace_){}
    , decltype(_impl_.command_type_name_){}
    , decltype(_impl_.type_){0}
    , decltype(_impl_.mql_error_code_){0}
    , decltype(_impl_.commandid_){int64_t{0}}
    , decltype(_impl_.mql_error_int_code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.error_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.mql_error_description_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.mql_error_description_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.stack_trace_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.stack_trace_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.command_type_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.command_type_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Error::~Error() {
  // @@protoc_insertion_point(destructor:mt4_term_api.Error)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Error::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.properties_.~RepeatedPtrField();
  _impl_.error_code_.Destroy();
  _impl_.error_message_.Destroy();
  _impl_.mql_error_description_.Destroy();
  _impl_.stack_trace_.Destroy();
  _impl_.command_type_name_.Destroy();
}

void Error::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Error::Clear() {
// @@protoc_insertion_point(message_clear_start:mt4_term_api.Error)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.properties_.Clear();
  _impl_.error_code_.ClearToEmpty();
  _impl_.error_message_.ClearToEmpty();
  _impl_.mql_error_description_.ClearToEmpty();
  _impl_.stack_trace_.ClearToEmpty();
  _impl_.command_type_name_.ClearToEmpty();
  ::memset(&_impl_.type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.mql_error_int_code_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.mql_error_int_code_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Error::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .mt4_term_api.ErrorType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::mt4_term_api::ErrorType>(val));
        } else
          goto handle_unusual;
        continue;
      // string error_code = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error_code();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt4_term_api.Error.error_code"));
        } else
          goto handle_unusual;
        continue;
      // string error_message = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_error_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt4_term_api.Error.error_message"));
        } else
          goto handle_unusual;
        continue;
      // .mt4_term_api.MqlErrorCode mql_error_code = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_mql_error_code(static_cast<::mt4_term_api::MqlErrorCode>(val));
        } else
          goto handle_unusual;
        continue;
      // int32 mql_error_int_code = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.mql_error_int_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string mql_error_description = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_mql_error_description();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt4_term_api.Error.mql_error_description"));
        } else
          goto handle_unusual;
        continue;
      // string stack_trace = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          auto str = _internal_mutable_stack_trace();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt4_term_api.Error.stack_trace"));
        } else
          goto handle_unusual;
        continue;
      // string command_type_name = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_command_type_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt4_term_api.Error.command_type_name"));
        } else
          goto handle_unusual;
        continue;
      // int64 commandId = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          _impl_.commandid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .mt4_term_api.ErrorProperty properties = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_properties(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<106>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Error::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mt4_term_api.Error)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .mt4_term_api.ErrorType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // string error_code = 2;
  if (!this->_internal_error_code().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_code().data(), static_cast<int>(this->_internal_error_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt4_term_api.Error.error_code");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error_code(), target);
  }

  // string error_message = 3;
  if (!this->_internal_error_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_message().data(), static_cast<int>(this->_internal_error_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt4_term_api.Error.error_message");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_error_message(), target);
  }

  // .mt4_term_api.MqlErrorCode mql_error_code = 4;
  if (this->_internal_mql_error_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_mql_error_code(), target);
  }

  // int32 mql_error_int_code = 5;
  if (this->_internal_mql_error_int_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_mql_error_int_code(), target);
  }

  // string mql_error_description = 6;
  if (!this->_internal_mql_error_description().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_mql_error_description().data(), static_cast<int>(this->_internal_mql_error_description().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt4_term_api.Error.mql_error_description");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_mql_error_description(), target);
  }

  // string stack_trace = 10;
  if (!this->_internal_stack_trace().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_stack_trace().data(), static_cast<int>(this->_internal_stack_trace().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt4_term_api.Error.stack_trace");
    target = stream->WriteStringMaybeAliased(
        10, this->_internal_stack_trace(), target);
  }

  // string command_type_name = 11;
  if (!this->_internal_command_type_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_command_type_name().data(), static_cast<int>(this->_internal_command_type_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt4_term_api.Error.command_type_name");
    target = stream->WriteStringMaybeAliased(
        11, this->_internal_command_type_name(), target);
  }

  // int64 commandId = 12;
  if (this->_internal_commandid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(12, this->_internal_commandid(), target);
  }

  // repeated .mt4_term_api.ErrorProperty properties = 13;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_properties_size()); i < n; i++) {
    const auto& repfield = this->_internal_properties(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(13, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mt4_term_api.Error)
  return target;
}

size_t Error::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mt4_term_api.Error)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .mt4_term_api.ErrorProperty properties = 13;
  total_size += 1UL * this->_internal_properties_size();
  for (const auto& msg : this->_impl_.properties_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string error_code = 2;
  if (!this->_internal_error_code().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_code());
  }

  // string error_message = 3;
  if (!this->_internal_error_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_message());
  }

  // string mql_error_description = 6;
  if (!this->_internal_mql_error_description().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_mql_error_description());
  }

  // string stack_trace = 10;
  if (!this->_internal_stack_trace().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_stack_trace());
  }

  // string command_type_name = 11;
  if (!this->_internal_command_type_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_command_type_name());
  }

  // .mt4_term_api.ErrorType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // .mt4_term_api.MqlErrorCode mql_error_code = 4;
  if (this->_internal_mql_error_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_mql_error_code());
  }

  // int64 commandId = 12;
  if (this->_internal_commandid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_commandid());
  }

  // int32 mql_error_int_code = 5;
  if (this->_internal_mql_error_int_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_mql_error_int_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Error::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Error::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Error::GetClassData() const { return &_class_data_; }


void Error::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Error*>(&to_msg);
  auto& from = static_cast<const Error&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mt4_term_api.Error)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.properties_.MergeFrom(from._impl_.properties_);
  if (!from._internal_error_code().empty()) {
    _this->_internal_set_error_code(from._internal_error_code());
  }
  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  if (!from._internal_mql_error_description().empty()) {
    _this->_internal_set_mql_error_description(from._internal_mql_error_description());
  }
  if (!from._internal_stack_trace().empty()) {
    _this->_internal_set_stack_trace(from._internal_stack_trace());
  }
  if (!from._internal_command_type_name().empty()) {
    _this->_internal_set_command_type_name(from._internal_command_type_name());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_mql_error_code() != 0) {
    _this->_internal_set_mql_error_code(from._internal_mql_error_code());
  }
  if (from._internal_commandid() != 0) {
    _this->_internal_set_commandid(from._internal_commandid());
  }
  if (from._internal_mql_error_int_code() != 0) {
    _this->_internal_set_mql_error_int_code(from._internal_mql_error_int_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Error::CopyFrom(const Error& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mt4_term_api.Error)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Error::IsInitialized() const {
  return true;
}

void Error::InternalSwap(Error* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.properties_.InternalSwap(&other->_impl_.properties_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_code_, lhs_arena,
      &other->_impl_.error_code_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_message_, lhs_arena,
      &other->_impl_.error_message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.mql_error_description_, lhs_arena,
      &other->_impl_.mql_error_description_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.stack_trace_, lhs_arena,
      &other->_impl_.stack_trace_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.command_type_name_, lhs_arena,
      &other->_impl_.command_type_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Error, _impl_.mql_error_int_code_)
      + sizeof(Error::_impl_.mql_error_int_code_)
      - PROTOBUF_FIELD_OFFSET(Error, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Error::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mrpc_2dmt4_2derror_2eproto_getter, &descriptor_table_mrpc_2dmt4_2derror_2eproto_once,
      file_level_metadata_mrpc_2dmt4_2derror_2eproto[0]);
}

// ===================================================================

class ErrorProperty::_Internal {
 public:
};

ErrorProperty::ErrorProperty(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mt4_term_api.ErrorProperty)
}
ErrorProperty::ErrorProperty(const ErrorProperty& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ErrorProperty* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_arg_key_){}
    , decltype(_impl_.error_arg_value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_arg_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_arg_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_arg_key().empty()) {
    _this->_impl_.error_arg_key_.Set(from._internal_error_arg_key(), 
      _this->GetArenaForAllocation());
  }
  _impl_.error_arg_value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_arg_value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_arg_value().empty()) {
    _this->_impl_.error_arg_value_.Set(from._internal_error_arg_value(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:mt4_term_api.ErrorProperty)
}

inline void ErrorProperty::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.error_arg_key_){}
    , decltype(_impl_.error_arg_value_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.error_arg_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_arg_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.error_arg_value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_arg_value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ErrorProperty::~ErrorProperty() {
  // @@protoc_insertion_point(destructor:mt4_term_api.ErrorProperty)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ErrorProperty::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.error_arg_key_.Destroy();
  _impl_.error_arg_value_.Destroy();
}

void ErrorProperty::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ErrorProperty::Clear() {
// @@protoc_insertion_point(message_clear_start:mt4_term_api.ErrorProperty)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_arg_key_.ClearToEmpty();
  _impl_.error_arg_value_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ErrorProperty::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string error_arg_key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_error_arg_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt4_term_api.ErrorProperty.error_arg_key"));
        } else
          goto handle_unusual;
        continue;
      // string error_arg_value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error_arg_value();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt4_term_api.ErrorProperty.error_arg_value"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ErrorProperty::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mt4_term_api.ErrorProperty)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string error_arg_key = 1;
  if (!this->_internal_error_arg_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_arg_key().data(), static_cast<int>(this->_internal_error_arg_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt4_term_api.ErrorProperty.error_arg_key");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_error_arg_key(), target);
  }

  // string error_arg_value = 2;
  if (!this->_internal_error_arg_value().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_arg_value().data(), static_cast<int>(this->_internal_error_arg_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt4_term_api.ErrorProperty.error_arg_value");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error_arg_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mt4_term_api.ErrorProperty)
  return target;
}

size_t ErrorProperty::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mt4_term_api.ErrorProperty)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string error_arg_key = 1;
  if (!this->_internal_error_arg_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_arg_key());
  }

  // string error_arg_value = 2;
  if (!this->_internal_error_arg_value().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_arg_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ErrorProperty::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ErrorProperty::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ErrorProperty::GetClassData() const { return &_class_data_; }


void ErrorProperty::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ErrorProperty*>(&to_msg);
  auto& from = static_cast<const ErrorProperty&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mt4_term_api.ErrorProperty)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error_arg_key().empty()) {
    _this->_internal_set_error_arg_key(from._internal_error_arg_key());
  }
  if (!from._internal_error_arg_value().empty()) {
    _this->_internal_set_error_arg_value(from._internal_error_arg_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ErrorProperty::CopyFrom(const ErrorProperty& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mt4_term_api.ErrorProperty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ErrorProperty::IsInitialized() const {
  return true;
}

void ErrorProperty::InternalSwap(ErrorProperty* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_arg_key_, lhs_arena,
      &other->_impl_.error_arg_key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_arg_value_, lhs_arena,
      &other->_impl_.error_arg_value_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata ErrorProperty::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mrpc_2dmt4_2derror_2eproto_getter, &descriptor_table_mrpc_2dmt4_2derror_2eproto_once,
      file_level_metadata_mrpc_2dmt4_2derror_2eproto[1]);
}

// ===================================================================

class LogFileInfo::_Internal {
 public:
};

LogFileInfo::LogFileInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mt4_term_api.LogFileInfo)
}
LogFileInfo::LogFileInfo(const LogFileInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LogFileInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.full_path_){}
    , decltype(_impl_.name_){}
    , decltype(_impl_.content_){}
    , decltype(_impl_.log_type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.full_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.full_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_full_path().empty()) {
    _this->_impl_.full_path_.Set(from._internal_full_path(), 
      _this->GetArenaForAllocation());
  }
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_content().empty()) {
    _this->_impl_.content_.Set(from._internal_content(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.log_type_ = from._impl_.log_type_;
  // @@protoc_insertion_point(copy_constructor:mt4_term_api.LogFileInfo)
}

inline void LogFileInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.full_path_){}
    , decltype(_impl_.name_){}
    , decltype(_impl_.content_){}
    , decltype(_impl_.log_type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.full_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.full_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LogFileInfo::~LogFileInfo() {
  // @@protoc_insertion_point(destructor:mt4_term_api.LogFileInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LogFileInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.full_path_.Destroy();
  _impl_.name_.Destroy();
  _impl_.content_.Destroy();
}

void LogFileInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LogFileInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:mt4_term_api.LogFileInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.full_path_.ClearToEmpty();
  _impl_.name_.ClearToEmpty();
  _impl_.content_.ClearToEmpty();
  _impl_.log_type_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LogFileInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .mt4_term_api.LogType log_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_log_type(static_cast<::mt4_term_api::LogType>(val));
        } else
          goto handle_unusual;
        continue;
      // string full_path = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_full_path();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt4_term_api.LogFileInfo.full_path"));
        } else
          goto handle_unusual;
        continue;
      // string name = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt4_term_api.LogFileInfo.name"));
        } else
          goto handle_unusual;
        continue;
      // string content = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_content();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt4_term_api.LogFileInfo.content"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LogFileInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mt4_term_api.LogFileInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .mt4_term_api.LogType log_type = 1;
  if (this->_internal_log_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_log_type(), target);
  }

  // string full_path = 2;
  if (!this->_internal_full_path().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_full_path().data(), static_cast<int>(this->_internal_full_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt4_term_api.LogFileInfo.full_path");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_full_path(), target);
  }

  // string name = 3;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt4_term_api.LogFileInfo.name");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_name(), target);
  }

  // string content = 4;
  if (!this->_internal_content().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_content().data(), static_cast<int>(this->_internal_content().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt4_term_api.LogFileInfo.content");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_content(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mt4_term_api.LogFileInfo)
  return target;
}

size_t LogFileInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mt4_term_api.LogFileInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string full_path = 2;
  if (!this->_internal_full_path().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_full_path());
  }

  // string name = 3;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string content = 4;
  if (!this->_internal_content().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_content());
  }

  // .mt4_term_api.LogType log_type = 1;
  if (this->_internal_log_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_log_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LogFileInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LogFileInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LogFileInfo::GetClassData() const { return &_class_data_; }


void LogFileInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LogFileInfo*>(&to_msg);
  auto& from = static_cast<const LogFileInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mt4_term_api.LogFileInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_full_path().empty()) {
    _this->_internal_set_full_path(from._internal_full_path());
  }
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  if (from._internal_log_type() != 0) {
    _this->_internal_set_log_type(from._internal_log_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LogFileInfo::CopyFrom(const LogFileInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mt4_term_api.LogFileInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogFileInfo::IsInitialized() const {
  return true;
}

void LogFileInfo::InternalSwap(LogFileInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.full_path_, lhs_arena,
      &other->_impl_.full_path_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.content_, lhs_arena,
      &other->_impl_.content_, rhs_arena
  );
  swap(_impl_.log_type_, other->_impl_.log_type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata LogFileInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mrpc_2dmt4_2derror_2eproto_getter, &descriptor_table_mrpc_2dmt4_2derror_2eproto_once,
      file_level_metadata_mrpc_2dmt4_2derror_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace mt4_term_api
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mt4_term_api::Error*
Arena::CreateMaybeMessage< ::mt4_term_api::Error >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt4_term_api::Error >(arena);
}
template<> PROTOBUF_NOINLINE ::mt4_term_api::ErrorProperty*
Arena::CreateMaybeMessage< ::mt4_term_api::ErrorProperty >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt4_term_api::ErrorProperty >(arena);
}
template<> PROTOBUF_NOINLINE ::mt4_term_api::LogFileInfo*
Arena::CreateMaybeMessage< ::mt4_term_api::LogFileInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt4_term_api::LogFileInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
