// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mt4-term-api-demo-account.proto

#include "mt4-term-api-demo-account.pb.h"
#include "mt4-term-api-demo-account.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace mt4_term_api {

static const char* DemoAccount_method_names[] = {
  "/mt4_term_api.DemoAccount/OpenDemoAccount",
  "/mt4_term_api.DemoAccount/DemoOpenAccountInteractive",
};

std::unique_ptr< DemoAccount::Stub> DemoAccount::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DemoAccount::Stub> stub(new DemoAccount::Stub(channel, options));
  return stub;
}

DemoAccount::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_OpenDemoAccount_(DemoAccount_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DemoOpenAccountInteractive_(DemoAccount_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status DemoAccount::Stub::OpenDemoAccount(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest& request, ::mt4_term_api::GuiDemoOpenAccountReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt4_term_api::GuiDemoOpenAccountRequest, ::mt4_term_api::GuiDemoOpenAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OpenDemoAccount_, context, request, response);
}

void DemoAccount::Stub::async::OpenDemoAccount(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest* request, ::mt4_term_api::GuiDemoOpenAccountReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt4_term_api::GuiDemoOpenAccountRequest, ::mt4_term_api::GuiDemoOpenAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OpenDemoAccount_, context, request, response, std::move(f));
}

void DemoAccount::Stub::async::OpenDemoAccount(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest* request, ::mt4_term_api::GuiDemoOpenAccountReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OpenDemoAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt4_term_api::GuiDemoOpenAccountReply>* DemoAccount::Stub::PrepareAsyncOpenDemoAccountRaw(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt4_term_api::GuiDemoOpenAccountReply, ::mt4_term_api::GuiDemoOpenAccountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OpenDemoAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt4_term_api::GuiDemoOpenAccountReply>* DemoAccount::Stub::AsyncOpenDemoAccountRaw(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOpenDemoAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>* DemoAccount::Stub::DemoOpenAccountInteractiveRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>::Create(channel_.get(), rpcmethod_DemoOpenAccountInteractive_, context);
}

void DemoAccount::Stub::async::DemoOpenAccountInteractive(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::mt4_term_api::GuiDemoInteractiveClientMessage,::mt4_term_api::GuiDemoInteractiveServerMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::mt4_term_api::GuiDemoInteractiveClientMessage,::mt4_term_api::GuiDemoInteractiveServerMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_DemoOpenAccountInteractive_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>* DemoAccount::Stub::AsyncDemoOpenAccountInteractiveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>::Create(channel_.get(), cq, rpcmethod_DemoOpenAccountInteractive_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>* DemoAccount::Stub::PrepareAsyncDemoOpenAccountInteractiveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>::Create(channel_.get(), cq, rpcmethod_DemoOpenAccountInteractive_, context, false, nullptr);
}

DemoAccount::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DemoAccount_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DemoAccount::Service, ::mt4_term_api::GuiDemoOpenAccountRequest, ::mt4_term_api::GuiDemoOpenAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DemoAccount::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt4_term_api::GuiDemoOpenAccountRequest* req,
             ::mt4_term_api::GuiDemoOpenAccountReply* resp) {
               return service->OpenDemoAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DemoAccount_method_names[1],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< DemoAccount::Service, ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>(
          [](DemoAccount::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::mt4_term_api::GuiDemoInteractiveServerMessage,
             ::mt4_term_api::GuiDemoInteractiveClientMessage>* stream) {
               return service->DemoOpenAccountInteractive(ctx, stream);
             }, this)));
}

DemoAccount::Service::~Service() {
}

::grpc::Status DemoAccount::Service::OpenDemoAccount(::grpc::ServerContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest* request, ::mt4_term_api::GuiDemoOpenAccountReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DemoAccount::Service::DemoOpenAccountInteractive(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::mt4_term_api::GuiDemoInteractiveServerMessage, ::mt4_term_api::GuiDemoInteractiveClientMessage>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mt4_term_api

