// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mt4-term-api-subscriptions.proto
#ifndef GRPC_mt4_2dterm_2dapi_2dsubscriptions_2eproto__INCLUDED
#define GRPC_mt4_2dterm_2dapi_2dsubscriptions_2eproto__INCLUDED

#include "mt4-term-api-subscriptions.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace mt4_term_api {

class SubscriptionService final {
 public:
  static constexpr char const* service_full_name() {
    return "mt4_term_api.SubscriptionService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Streams real-time order/trade events.
    // Requires 'id' header — use GetId to generate.
    // Swagger does not support streaming — use /subscription-stream interactive viewer.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::mt4_term_api::OnTradeReply>> OnTrade(::grpc::ClientContext* context, const ::mt4_term_api::OnTradeRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::mt4_term_api::OnTradeReply>>(OnTradeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnTradeReply>> AsyncOnTrade(::grpc::ClientContext* context, const ::mt4_term_api::OnTradeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnTradeReply>>(AsyncOnTradeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnTradeReply>> PrepareAsyncOnTrade(::grpc::ClientContext* context, const ::mt4_term_api::OnTradeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnTradeReply>>(PrepareAsyncOnTradeRaw(context, request, cq));
    }
    // Streams the tickets of currently opened orders as they change.
    // Requires 'id' header — use GetId to generate.
    // Swagger does not support streaming — use /subscription-stream interactive viewer.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::mt4_term_api::OnOpenedOrdersTicketsReply>> OnOpenedOrdersTickets(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::mt4_term_api::OnOpenedOrdersTicketsReply>>(OnOpenedOrdersTicketsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnOpenedOrdersTicketsReply>> AsyncOnOpenedOrdersTickets(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnOpenedOrdersTicketsReply>>(AsyncOnOpenedOrdersTicketsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnOpenedOrdersTicketsReply>> PrepareAsyncOnOpenedOrdersTickets(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnOpenedOrdersTicketsReply>>(PrepareAsyncOnOpenedOrdersTicketsRaw(context, request, cq));
    }
    // Streams the live profit of currently opened orders.
    // Requires 'id' header — use GetId to generate.
    // Swagger does not support streaming — use /subscription-stream interactive viewer.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::mt4_term_api::OnOpenedOrdersProfitReply>> OnOpenedOrdersProfit(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::mt4_term_api::OnOpenedOrdersProfitReply>>(OnOpenedOrdersProfitRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnOpenedOrdersProfitReply>> AsyncOnOpenedOrdersProfit(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnOpenedOrdersProfitReply>>(AsyncOnOpenedOrdersProfitRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnOpenedOrdersProfitReply>> PrepareAsyncOnOpenedOrdersProfit(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnOpenedOrdersProfitReply>>(PrepareAsyncOnOpenedOrdersProfitRaw(context, request, cq));
    }
    // Streams real-time ticks for the given symbols.
    // Requires 'id' header — use GetId to generate.
    // Swagger does not support streaming — use /subscription-stream interactive viewer.
    // [DefaultValues]
    // {
    //   "symbolNames": "EURUSD,BTCUSD"
    // }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::mt4_term_api::OnSymbolTickReply>> OnSymbolTick(::grpc::ClientContext* context, const ::mt4_term_api::OnSymbolTickRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::mt4_term_api::OnSymbolTickReply>>(OnSymbolTickRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnSymbolTickReply>> AsyncOnSymbolTick(::grpc::ClientContext* context, const ::mt4_term_api::OnSymbolTickRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnSymbolTickReply>>(AsyncOnSymbolTickRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnSymbolTickReply>> PrepareAsyncOnSymbolTick(::grpc::ClientContext* context, const ::mt4_term_api::OnSymbolTickRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnSymbolTickReply>>(PrepareAsyncOnSymbolTickRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Streams real-time order/trade events.
      // Requires 'id' header — use GetId to generate.
      // Swagger does not support streaming — use /subscription-stream interactive viewer.
      virtual void OnTrade(::grpc::ClientContext* context, const ::mt4_term_api::OnTradeRequest* request, ::grpc::ClientReadReactor< ::mt4_term_api::OnTradeReply>* reactor) = 0;
      // Streams the tickets of currently opened orders as they change.
      // Requires 'id' header — use GetId to generate.
      // Swagger does not support streaming — use /subscription-stream interactive viewer.
      virtual void OnOpenedOrdersTickets(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest* request, ::grpc::ClientReadReactor< ::mt4_term_api::OnOpenedOrdersTicketsReply>* reactor) = 0;
      // Streams the live profit of currently opened orders.
      // Requires 'id' header — use GetId to generate.
      // Swagger does not support streaming — use /subscription-stream interactive viewer.
      virtual void OnOpenedOrdersProfit(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest* request, ::grpc::ClientReadReactor< ::mt4_term_api::OnOpenedOrdersProfitReply>* reactor) = 0;
      // Streams real-time ticks for the given symbols.
      // Requires 'id' header — use GetId to generate.
      // Swagger does not support streaming — use /subscription-stream interactive viewer.
      // [DefaultValues]
      // {
      //   "symbolNames": "EURUSD,BTCUSD"
      // }
      virtual void OnSymbolTick(::grpc::ClientContext* context, const ::mt4_term_api::OnSymbolTickRequest* request, ::grpc::ClientReadReactor< ::mt4_term_api::OnSymbolTickReply>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::mt4_term_api::OnTradeReply>* OnTradeRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnTradeRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnTradeReply>* AsyncOnTradeRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnTradeRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnTradeReply>* PrepareAsyncOnTradeRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnTradeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::mt4_term_api::OnOpenedOrdersTicketsReply>* OnOpenedOrdersTicketsRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnOpenedOrdersTicketsReply>* AsyncOnOpenedOrdersTicketsRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnOpenedOrdersTicketsReply>* PrepareAsyncOnOpenedOrdersTicketsRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::mt4_term_api::OnOpenedOrdersProfitReply>* OnOpenedOrdersProfitRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnOpenedOrdersProfitReply>* AsyncOnOpenedOrdersProfitRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnOpenedOrdersProfitReply>* PrepareAsyncOnOpenedOrdersProfitRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::mt4_term_api::OnSymbolTickReply>* OnSymbolTickRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnSymbolTickRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnSymbolTickReply>* AsyncOnSymbolTickRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnSymbolTickRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::mt4_term_api::OnSymbolTickReply>* PrepareAsyncOnSymbolTickRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnSymbolTickRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::mt4_term_api::OnTradeReply>> OnTrade(::grpc::ClientContext* context, const ::mt4_term_api::OnTradeRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::mt4_term_api::OnTradeReply>>(OnTradeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnTradeReply>> AsyncOnTrade(::grpc::ClientContext* context, const ::mt4_term_api::OnTradeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnTradeReply>>(AsyncOnTradeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnTradeReply>> PrepareAsyncOnTrade(::grpc::ClientContext* context, const ::mt4_term_api::OnTradeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnTradeReply>>(PrepareAsyncOnTradeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::mt4_term_api::OnOpenedOrdersTicketsReply>> OnOpenedOrdersTickets(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::mt4_term_api::OnOpenedOrdersTicketsReply>>(OnOpenedOrdersTicketsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnOpenedOrdersTicketsReply>> AsyncOnOpenedOrdersTickets(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnOpenedOrdersTicketsReply>>(AsyncOnOpenedOrdersTicketsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnOpenedOrdersTicketsReply>> PrepareAsyncOnOpenedOrdersTickets(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnOpenedOrdersTicketsReply>>(PrepareAsyncOnOpenedOrdersTicketsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::mt4_term_api::OnOpenedOrdersProfitReply>> OnOpenedOrdersProfit(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::mt4_term_api::OnOpenedOrdersProfitReply>>(OnOpenedOrdersProfitRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnOpenedOrdersProfitReply>> AsyncOnOpenedOrdersProfit(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnOpenedOrdersProfitReply>>(AsyncOnOpenedOrdersProfitRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnOpenedOrdersProfitReply>> PrepareAsyncOnOpenedOrdersProfit(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnOpenedOrdersProfitReply>>(PrepareAsyncOnOpenedOrdersProfitRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::mt4_term_api::OnSymbolTickReply>> OnSymbolTick(::grpc::ClientContext* context, const ::mt4_term_api::OnSymbolTickRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::mt4_term_api::OnSymbolTickReply>>(OnSymbolTickRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnSymbolTickReply>> AsyncOnSymbolTick(::grpc::ClientContext* context, const ::mt4_term_api::OnSymbolTickRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnSymbolTickReply>>(AsyncOnSymbolTickRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnSymbolTickReply>> PrepareAsyncOnSymbolTick(::grpc::ClientContext* context, const ::mt4_term_api::OnSymbolTickRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::mt4_term_api::OnSymbolTickReply>>(PrepareAsyncOnSymbolTickRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void OnTrade(::grpc::ClientContext* context, const ::mt4_term_api::OnTradeRequest* request, ::grpc::ClientReadReactor< ::mt4_term_api::OnTradeReply>* reactor) override;
      void OnOpenedOrdersTickets(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest* request, ::grpc::ClientReadReactor< ::mt4_term_api::OnOpenedOrdersTicketsReply>* reactor) override;
      void OnOpenedOrdersProfit(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest* request, ::grpc::ClientReadReactor< ::mt4_term_api::OnOpenedOrdersProfitReply>* reactor) override;
      void OnSymbolTick(::grpc::ClientContext* context, const ::mt4_term_api::OnSymbolTickRequest* request, ::grpc::ClientReadReactor< ::mt4_term_api::OnSymbolTickReply>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::mt4_term_api::OnTradeReply>* OnTradeRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnTradeRequest& request) override;
    ::grpc::ClientAsyncReader< ::mt4_term_api::OnTradeReply>* AsyncOnTradeRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnTradeRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::mt4_term_api::OnTradeReply>* PrepareAsyncOnTradeRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnTradeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::mt4_term_api::OnOpenedOrdersTicketsReply>* OnOpenedOrdersTicketsRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest& request) override;
    ::grpc::ClientAsyncReader< ::mt4_term_api::OnOpenedOrdersTicketsReply>* AsyncOnOpenedOrdersTicketsRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::mt4_term_api::OnOpenedOrdersTicketsReply>* PrepareAsyncOnOpenedOrdersTicketsRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::mt4_term_api::OnOpenedOrdersProfitReply>* OnOpenedOrdersProfitRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest& request) override;
    ::grpc::ClientAsyncReader< ::mt4_term_api::OnOpenedOrdersProfitReply>* AsyncOnOpenedOrdersProfitRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::mt4_term_api::OnOpenedOrdersProfitReply>* PrepareAsyncOnOpenedOrdersProfitRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::mt4_term_api::OnSymbolTickReply>* OnSymbolTickRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnSymbolTickRequest& request) override;
    ::grpc::ClientAsyncReader< ::mt4_term_api::OnSymbolTickReply>* AsyncOnSymbolTickRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnSymbolTickRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::mt4_term_api::OnSymbolTickReply>* PrepareAsyncOnSymbolTickRaw(::grpc::ClientContext* context, const ::mt4_term_api::OnSymbolTickRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_OnTrade_;
    const ::grpc::internal::RpcMethod rpcmethod_OnOpenedOrdersTickets_;
    const ::grpc::internal::RpcMethod rpcmethod_OnOpenedOrdersProfit_;
    const ::grpc::internal::RpcMethod rpcmethod_OnSymbolTick_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Streams real-time order/trade events.
    // Requires 'id' header — use GetId to generate.
    // Swagger does not support streaming — use /subscription-stream interactive viewer.
    virtual ::grpc::Status OnTrade(::grpc::ServerContext* context, const ::mt4_term_api::OnTradeRequest* request, ::grpc::ServerWriter< ::mt4_term_api::OnTradeReply>* writer);
    // Streams the tickets of currently opened orders as they change.
    // Requires 'id' header — use GetId to generate.
    // Swagger does not support streaming — use /subscription-stream interactive viewer.
    virtual ::grpc::Status OnOpenedOrdersTickets(::grpc::ServerContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest* request, ::grpc::ServerWriter< ::mt4_term_api::OnOpenedOrdersTicketsReply>* writer);
    // Streams the live profit of currently opened orders.
    // Requires 'id' header — use GetId to generate.
    // Swagger does not support streaming — use /subscription-stream interactive viewer.
    virtual ::grpc::Status OnOpenedOrdersProfit(::grpc::ServerContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest* request, ::grpc::ServerWriter< ::mt4_term_api::OnOpenedOrdersProfitReply>* writer);
    // Streams real-time ticks for the given symbols.
    // Requires 'id' header — use GetId to generate.
    // Swagger does not support streaming — use /subscription-stream interactive viewer.
    // [DefaultValues]
    // {
    //   "symbolNames": "EURUSD,BTCUSD"
    // }
    virtual ::grpc::Status OnSymbolTick(::grpc::ServerContext* context, const ::mt4_term_api::OnSymbolTickRequest* request, ::grpc::ServerWriter< ::mt4_term_api::OnSymbolTickReply>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_OnTrade : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OnTrade() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_OnTrade() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnTrade(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnTradeRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnTradeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnTrade(::grpc::ServerContext* context, ::mt4_term_api::OnTradeRequest* request, ::grpc::ServerAsyncWriter< ::mt4_term_api::OnTradeReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_OnOpenedOrdersTickets : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OnOpenedOrdersTickets() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_OnOpenedOrdersTickets() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnOpenedOrdersTickets(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnOpenedOrdersTicketsRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnOpenedOrdersTicketsReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnOpenedOrdersTickets(::grpc::ServerContext* context, ::mt4_term_api::OnOpenedOrdersTicketsRequest* request, ::grpc::ServerAsyncWriter< ::mt4_term_api::OnOpenedOrdersTicketsReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_OnOpenedOrdersProfit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OnOpenedOrdersProfit() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_OnOpenedOrdersProfit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnOpenedOrdersProfit(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnOpenedOrdersProfitRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnOpenedOrdersProfitReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnOpenedOrdersProfit(::grpc::ServerContext* context, ::mt4_term_api::OnOpenedOrdersProfitRequest* request, ::grpc::ServerAsyncWriter< ::mt4_term_api::OnOpenedOrdersProfitReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_OnSymbolTick : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OnSymbolTick() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_OnSymbolTick() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSymbolTick(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnSymbolTickRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnSymbolTickReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnSymbolTick(::grpc::ServerContext* context, ::mt4_term_api::OnSymbolTickRequest* request, ::grpc::ServerAsyncWriter< ::mt4_term_api::OnSymbolTickReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(3, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_OnTrade<WithAsyncMethod_OnOpenedOrdersTickets<WithAsyncMethod_OnOpenedOrdersProfit<WithAsyncMethod_OnSymbolTick<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_OnTrade : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OnTrade() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::mt4_term_api::OnTradeRequest, ::mt4_term_api::OnTradeReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mt4_term_api::OnTradeRequest* request) { return this->OnTrade(context, request); }));
    }
    ~WithCallbackMethod_OnTrade() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnTrade(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnTradeRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnTradeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::mt4_term_api::OnTradeReply>* OnTrade(
      ::grpc::CallbackServerContext* /*context*/, const ::mt4_term_api::OnTradeRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_OnOpenedOrdersTickets : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OnOpenedOrdersTickets() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::mt4_term_api::OnOpenedOrdersTicketsRequest, ::mt4_term_api::OnOpenedOrdersTicketsReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mt4_term_api::OnOpenedOrdersTicketsRequest* request) { return this->OnOpenedOrdersTickets(context, request); }));
    }
    ~WithCallbackMethod_OnOpenedOrdersTickets() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnOpenedOrdersTickets(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnOpenedOrdersTicketsRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnOpenedOrdersTicketsReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::mt4_term_api::OnOpenedOrdersTicketsReply>* OnOpenedOrdersTickets(
      ::grpc::CallbackServerContext* /*context*/, const ::mt4_term_api::OnOpenedOrdersTicketsRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_OnOpenedOrdersProfit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OnOpenedOrdersProfit() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::mt4_term_api::OnOpenedOrdersProfitRequest, ::mt4_term_api::OnOpenedOrdersProfitReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mt4_term_api::OnOpenedOrdersProfitRequest* request) { return this->OnOpenedOrdersProfit(context, request); }));
    }
    ~WithCallbackMethod_OnOpenedOrdersProfit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnOpenedOrdersProfit(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnOpenedOrdersProfitRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnOpenedOrdersProfitReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::mt4_term_api::OnOpenedOrdersProfitReply>* OnOpenedOrdersProfit(
      ::grpc::CallbackServerContext* /*context*/, const ::mt4_term_api::OnOpenedOrdersProfitRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_OnSymbolTick : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OnSymbolTick() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackServerStreamingHandler< ::mt4_term_api::OnSymbolTickRequest, ::mt4_term_api::OnSymbolTickReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mt4_term_api::OnSymbolTickRequest* request) { return this->OnSymbolTick(context, request); }));
    }
    ~WithCallbackMethod_OnSymbolTick() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSymbolTick(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnSymbolTickRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnSymbolTickReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::mt4_term_api::OnSymbolTickReply>* OnSymbolTick(
      ::grpc::CallbackServerContext* /*context*/, const ::mt4_term_api::OnSymbolTickRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_OnTrade<WithCallbackMethod_OnOpenedOrdersTickets<WithCallbackMethod_OnOpenedOrdersProfit<WithCallbackMethod_OnSymbolTick<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_OnTrade : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OnTrade() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_OnTrade() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnTrade(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnTradeRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnTradeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_OnOpenedOrdersTickets : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OnOpenedOrdersTickets() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_OnOpenedOrdersTickets() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnOpenedOrdersTickets(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnOpenedOrdersTicketsRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnOpenedOrdersTicketsReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_OnOpenedOrdersProfit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OnOpenedOrdersProfit() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_OnOpenedOrdersProfit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnOpenedOrdersProfit(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnOpenedOrdersProfitRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnOpenedOrdersProfitReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_OnSymbolTick : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OnSymbolTick() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_OnSymbolTick() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSymbolTick(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnSymbolTickRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnSymbolTickReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_OnTrade : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OnTrade() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_OnTrade() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnTrade(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnTradeRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnTradeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnTrade(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_OnOpenedOrdersTickets : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OnOpenedOrdersTickets() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_OnOpenedOrdersTickets() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnOpenedOrdersTickets(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnOpenedOrdersTicketsRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnOpenedOrdersTicketsReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnOpenedOrdersTickets(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_OnOpenedOrdersProfit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OnOpenedOrdersProfit() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_OnOpenedOrdersProfit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnOpenedOrdersProfit(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnOpenedOrdersProfitRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnOpenedOrdersProfitReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnOpenedOrdersProfit(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_OnSymbolTick : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OnSymbolTick() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_OnSymbolTick() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSymbolTick(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnSymbolTickRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnSymbolTickReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnSymbolTick(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(3, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OnTrade : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OnTrade() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->OnTrade(context, request); }));
    }
    ~WithRawCallbackMethod_OnTrade() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnTrade(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnTradeRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnTradeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* OnTrade(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OnOpenedOrdersTickets : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OnOpenedOrdersTickets() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->OnOpenedOrdersTickets(context, request); }));
    }
    ~WithRawCallbackMethod_OnOpenedOrdersTickets() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnOpenedOrdersTickets(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnOpenedOrdersTicketsRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnOpenedOrdersTicketsReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* OnOpenedOrdersTickets(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OnOpenedOrdersProfit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OnOpenedOrdersProfit() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->OnOpenedOrdersProfit(context, request); }));
    }
    ~WithRawCallbackMethod_OnOpenedOrdersProfit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnOpenedOrdersProfit(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnOpenedOrdersProfitRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnOpenedOrdersProfitReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* OnOpenedOrdersProfit(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OnSymbolTick : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OnSymbolTick() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->OnSymbolTick(context, request); }));
    }
    ~WithRawCallbackMethod_OnSymbolTick() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSymbolTick(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnSymbolTickRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnSymbolTickReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* OnSymbolTick(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_OnTrade : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_OnTrade() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::mt4_term_api::OnTradeRequest, ::mt4_term_api::OnTradeReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::mt4_term_api::OnTradeRequest, ::mt4_term_api::OnTradeReply>* streamer) {
                       return this->StreamedOnTrade(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_OnTrade() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OnTrade(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnTradeRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnTradeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedOnTrade(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::mt4_term_api::OnTradeRequest,::mt4_term_api::OnTradeReply>* server_split_streamer) = 0;
  };
  template <class BaseClass>
  class WithSplitStreamingMethod_OnOpenedOrdersTickets : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_OnOpenedOrdersTickets() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::mt4_term_api::OnOpenedOrdersTicketsRequest, ::mt4_term_api::OnOpenedOrdersTicketsReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::mt4_term_api::OnOpenedOrdersTicketsRequest, ::mt4_term_api::OnOpenedOrdersTicketsReply>* streamer) {
                       return this->StreamedOnOpenedOrdersTickets(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_OnOpenedOrdersTickets() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OnOpenedOrdersTickets(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnOpenedOrdersTicketsRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnOpenedOrdersTicketsReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedOnOpenedOrdersTickets(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::mt4_term_api::OnOpenedOrdersTicketsRequest,::mt4_term_api::OnOpenedOrdersTicketsReply>* server_split_streamer) = 0;
  };
  template <class BaseClass>
  class WithSplitStreamingMethod_OnOpenedOrdersProfit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_OnOpenedOrdersProfit() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::mt4_term_api::OnOpenedOrdersProfitRequest, ::mt4_term_api::OnOpenedOrdersProfitReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::mt4_term_api::OnOpenedOrdersProfitRequest, ::mt4_term_api::OnOpenedOrdersProfitReply>* streamer) {
                       return this->StreamedOnOpenedOrdersProfit(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_OnOpenedOrdersProfit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OnOpenedOrdersProfit(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnOpenedOrdersProfitRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnOpenedOrdersProfitReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedOnOpenedOrdersProfit(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::mt4_term_api::OnOpenedOrdersProfitRequest,::mt4_term_api::OnOpenedOrdersProfitReply>* server_split_streamer) = 0;
  };
  template <class BaseClass>
  class WithSplitStreamingMethod_OnSymbolTick : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_OnSymbolTick() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::mt4_term_api::OnSymbolTickRequest, ::mt4_term_api::OnSymbolTickReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::mt4_term_api::OnSymbolTickRequest, ::mt4_term_api::OnSymbolTickReply>* streamer) {
                       return this->StreamedOnSymbolTick(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_OnSymbolTick() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OnSymbolTick(::grpc::ServerContext* /*context*/, const ::mt4_term_api::OnSymbolTickRequest* /*request*/, ::grpc::ServerWriter< ::mt4_term_api::OnSymbolTickReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedOnSymbolTick(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::mt4_term_api::OnSymbolTickRequest,::mt4_term_api::OnSymbolTickReply>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_OnTrade<WithSplitStreamingMethod_OnOpenedOrdersTickets<WithSplitStreamingMethod_OnOpenedOrdersProfit<WithSplitStreamingMethod_OnSymbolTick<Service > > > > SplitStreamedService;
  typedef WithSplitStreamingMethod_OnTrade<WithSplitStreamingMethod_OnOpenedOrdersTickets<WithSplitStreamingMethod_OnOpenedOrdersProfit<WithSplitStreamingMethod_OnSymbolTick<Service > > > > StreamedService;
};

}  // namespace mt4_term_api


#endif  // GRPC_mt4_2dterm_2dapi_2dsubscriptions_2eproto__INCLUDED
