// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mt4-term-api-health-check.proto

#include "mt4-term-api-health-check.pb.h"
#include "mt4-term-api-health-check.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace mt4_term_api {

static const char* HealthService_method_names[] = {
  "/mt4_term_api.HealthService/HealthCheck",
  "/mt4_term_api.HealthService/CloseTerminal",
};

std::unique_ptr< HealthService::Stub> HealthService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HealthService::Stub> stub(new HealthService::Stub(channel, options));
  return stub;
}

HealthService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_HealthCheck_(HealthService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CloseTerminal_(HealthService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HealthService::Stub::HealthCheck(::grpc::ClientContext* context, const ::mt4_term_api::HealthCheckRequest& request, ::mt4_term_api::HealthCheckReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt4_term_api::HealthCheckRequest, ::mt4_term_api::HealthCheckReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HealthCheck_, context, request, response);
}

void HealthService::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::mt4_term_api::HealthCheckRequest* request, ::mt4_term_api::HealthCheckReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt4_term_api::HealthCheckRequest, ::mt4_term_api::HealthCheckReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, std::move(f));
}

void HealthService::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::mt4_term_api::HealthCheckRequest* request, ::mt4_term_api::HealthCheckReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt4_term_api::HealthCheckReply>* HealthService::Stub::PrepareAsyncHealthCheckRaw(::grpc::ClientContext* context, const ::mt4_term_api::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt4_term_api::HealthCheckReply, ::mt4_term_api::HealthCheckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HealthCheck_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt4_term_api::HealthCheckReply>* HealthService::Stub::AsyncHealthCheckRaw(::grpc::ClientContext* context, const ::mt4_term_api::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHealthCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HealthService::Stub::CloseTerminal(::grpc::ClientContext* context, const ::mt4_term_api::CloseTerminalRequest& request, ::mt4_term_api::CloseTerminalReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt4_term_api::CloseTerminalRequest, ::mt4_term_api::CloseTerminalReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CloseTerminal_, context, request, response);
}

void HealthService::Stub::async::CloseTerminal(::grpc::ClientContext* context, const ::mt4_term_api::CloseTerminalRequest* request, ::mt4_term_api::CloseTerminalReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt4_term_api::CloseTerminalRequest, ::mt4_term_api::CloseTerminalReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CloseTerminal_, context, request, response, std::move(f));
}

void HealthService::Stub::async::CloseTerminal(::grpc::ClientContext* context, const ::mt4_term_api::CloseTerminalRequest* request, ::mt4_term_api::CloseTerminalReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CloseTerminal_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt4_term_api::CloseTerminalReply>* HealthService::Stub::PrepareAsyncCloseTerminalRaw(::grpc::ClientContext* context, const ::mt4_term_api::CloseTerminalRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt4_term_api::CloseTerminalReply, ::mt4_term_api::CloseTerminalRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CloseTerminal_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt4_term_api::CloseTerminalReply>* HealthService::Stub::AsyncCloseTerminalRaw(::grpc::ClientContext* context, const ::mt4_term_api::CloseTerminalRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCloseTerminalRaw(context, request, cq);
  result->StartCall();
  return result;
}

HealthService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HealthService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HealthService::Service, ::mt4_term_api::HealthCheckRequest, ::mt4_term_api::HealthCheckReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HealthService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt4_term_api::HealthCheckRequest* req,
             ::mt4_term_api::HealthCheckReply* resp) {
               return service->HealthCheck(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HealthService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HealthService::Service, ::mt4_term_api::CloseTerminalRequest, ::mt4_term_api::CloseTerminalReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HealthService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt4_term_api::CloseTerminalRequest* req,
             ::mt4_term_api::CloseTerminalReply* resp) {
               return service->CloseTerminal(ctx, req, resp);
             }, this)));
}

HealthService::Service::~Service() {
}

::grpc::Status HealthService::Service::HealthCheck(::grpc::ServerContext* context, const ::mt4_term_api::HealthCheckRequest* request, ::mt4_term_api::HealthCheckReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HealthService::Service::CloseTerminal(::grpc::ServerContext* context, const ::mt4_term_api::CloseTerminalRequest* request, ::mt4_term_api::CloseTerminalReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mt4_term_api

