// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mt4-term-api-gui.proto
#ifndef GRPC_mt4_2dterm_2dapi_2dgui_2eproto__INCLUDED
#define GRPC_mt4_2dterm_2dapi_2dgui_2eproto__INCLUDED

#include "mt4-term-api-gui.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace mt4_term_api {

// Terminal-side GUI-automation service (implemented by mt4-framework-grpc, which
// P/Invokes mt4-term-gui.dll). The manager's DemoAccount service proxies to these.
class Gui final {
 public:
  static constexpr char const* service_full_name() {
    return "mt4_term_api.Gui";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status DemoOpenAccount(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest& request, ::mt4_term_api::GuiDemoOpenAccountReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt4_term_api::GuiDemoOpenAccountReply>> AsyncDemoOpenAccount(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt4_term_api::GuiDemoOpenAccountReply>>(AsyncDemoOpenAccountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt4_term_api::GuiDemoOpenAccountReply>> PrepareAsyncDemoOpenAccount(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt4_term_api::GuiDemoOpenAccountReply>>(PrepareAsyncDemoOpenAccountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>> DemoOpenAccountInteractive(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>>(DemoOpenAccountInteractiveRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>> AsyncDemoOpenAccountInteractive(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>>(AsyncDemoOpenAccountInteractiveRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>> PrepareAsyncDemoOpenAccountInteractive(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>>(PrepareAsyncDemoOpenAccountInteractiveRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void DemoOpenAccount(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest* request, ::mt4_term_api::GuiDemoOpenAccountReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DemoOpenAccount(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest* request, ::mt4_term_api::GuiDemoOpenAccountReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DemoOpenAccountInteractive(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::mt4_term_api::GuiDemoInteractiveClientMessage,::mt4_term_api::GuiDemoInteractiveServerMessage>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mt4_term_api::GuiDemoOpenAccountReply>* AsyncDemoOpenAccountRaw(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mt4_term_api::GuiDemoOpenAccountReply>* PrepareAsyncDemoOpenAccountRaw(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>* DemoOpenAccountInteractiveRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>* AsyncDemoOpenAccountInteractiveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>* PrepareAsyncDemoOpenAccountInteractiveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status DemoOpenAccount(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest& request, ::mt4_term_api::GuiDemoOpenAccountReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt4_term_api::GuiDemoOpenAccountReply>> AsyncDemoOpenAccount(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt4_term_api::GuiDemoOpenAccountReply>>(AsyncDemoOpenAccountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt4_term_api::GuiDemoOpenAccountReply>> PrepareAsyncDemoOpenAccount(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt4_term_api::GuiDemoOpenAccountReply>>(PrepareAsyncDemoOpenAccountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>> DemoOpenAccountInteractive(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>>(DemoOpenAccountInteractiveRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>> AsyncDemoOpenAccountInteractive(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>>(AsyncDemoOpenAccountInteractiveRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>> PrepareAsyncDemoOpenAccountInteractive(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>>(PrepareAsyncDemoOpenAccountInteractiveRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void DemoOpenAccount(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest* request, ::mt4_term_api::GuiDemoOpenAccountReply* response, std::function<void(::grpc::Status)>) override;
      void DemoOpenAccount(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest* request, ::mt4_term_api::GuiDemoOpenAccountReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DemoOpenAccountInteractive(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::mt4_term_api::GuiDemoInteractiveClientMessage,::mt4_term_api::GuiDemoInteractiveServerMessage>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mt4_term_api::GuiDemoOpenAccountReply>* AsyncDemoOpenAccountRaw(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mt4_term_api::GuiDemoOpenAccountReply>* PrepareAsyncDemoOpenAccountRaw(::grpc::ClientContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>* DemoOpenAccountInteractiveRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>* AsyncDemoOpenAccountInteractiveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>* PrepareAsyncDemoOpenAccountInteractiveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DemoOpenAccount_;
    const ::grpc::internal::RpcMethod rpcmethod_DemoOpenAccountInteractive_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status DemoOpenAccount(::grpc::ServerContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest* request, ::mt4_term_api::GuiDemoOpenAccountReply* response);
    virtual ::grpc::Status DemoOpenAccountInteractive(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::mt4_term_api::GuiDemoInteractiveServerMessage, ::mt4_term_api::GuiDemoInteractiveClientMessage>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_DemoOpenAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DemoOpenAccount() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DemoOpenAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DemoOpenAccount(::grpc::ServerContext* /*context*/, const ::mt4_term_api::GuiDemoOpenAccountRequest* /*request*/, ::mt4_term_api::GuiDemoOpenAccountReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDemoOpenAccount(::grpc::ServerContext* context, ::mt4_term_api::GuiDemoOpenAccountRequest* request, ::grpc::ServerAsyncResponseWriter< ::mt4_term_api::GuiDemoOpenAccountReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DemoOpenAccountInteractive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DemoOpenAccountInteractive() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_DemoOpenAccountInteractive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DemoOpenAccountInteractive(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mt4_term_api::GuiDemoInteractiveServerMessage, ::mt4_term_api::GuiDemoInteractiveClientMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDemoOpenAccountInteractive(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::mt4_term_api::GuiDemoInteractiveServerMessage, ::mt4_term_api::GuiDemoInteractiveClientMessage>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DemoOpenAccount<WithAsyncMethod_DemoOpenAccountInteractive<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_DemoOpenAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DemoOpenAccount() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::mt4_term_api::GuiDemoOpenAccountRequest, ::mt4_term_api::GuiDemoOpenAccountReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mt4_term_api::GuiDemoOpenAccountRequest* request, ::mt4_term_api::GuiDemoOpenAccountReply* response) { return this->DemoOpenAccount(context, request, response); }));}
    void SetMessageAllocatorFor_DemoOpenAccount(
        ::grpc::MessageAllocator< ::mt4_term_api::GuiDemoOpenAccountRequest, ::mt4_term_api::GuiDemoOpenAccountReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mt4_term_api::GuiDemoOpenAccountRequest, ::mt4_term_api::GuiDemoOpenAccountReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DemoOpenAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DemoOpenAccount(::grpc::ServerContext* /*context*/, const ::mt4_term_api::GuiDemoOpenAccountRequest* /*request*/, ::mt4_term_api::GuiDemoOpenAccountReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DemoOpenAccount(
      ::grpc::CallbackServerContext* /*context*/, const ::mt4_term_api::GuiDemoOpenAccountRequest* /*request*/, ::mt4_term_api::GuiDemoOpenAccountReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DemoOpenAccountInteractive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DemoOpenAccountInteractive() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->DemoOpenAccountInteractive(context); }));
    }
    ~WithCallbackMethod_DemoOpenAccountInteractive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DemoOpenAccountInteractive(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mt4_term_api::GuiDemoInteractiveServerMessage, ::mt4_term_api::GuiDemoInteractiveClientMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::mt4_term_api::GuiDemoInteractiveClientMessage, ::mt4_term_api::GuiDemoInteractiveServerMessage>* DemoOpenAccountInteractive(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_DemoOpenAccount<WithCallbackMethod_DemoOpenAccountInteractive<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DemoOpenAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DemoOpenAccount() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DemoOpenAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DemoOpenAccount(::grpc::ServerContext* /*context*/, const ::mt4_term_api::GuiDemoOpenAccountRequest* /*request*/, ::mt4_term_api::GuiDemoOpenAccountReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DemoOpenAccountInteractive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DemoOpenAccountInteractive() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_DemoOpenAccountInteractive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DemoOpenAccountInteractive(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mt4_term_api::GuiDemoInteractiveServerMessage, ::mt4_term_api::GuiDemoInteractiveClientMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DemoOpenAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DemoOpenAccount() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DemoOpenAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DemoOpenAccount(::grpc::ServerContext* /*context*/, const ::mt4_term_api::GuiDemoOpenAccountRequest* /*request*/, ::mt4_term_api::GuiDemoOpenAccountReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDemoOpenAccount(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DemoOpenAccountInteractive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DemoOpenAccountInteractive() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_DemoOpenAccountInteractive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DemoOpenAccountInteractive(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mt4_term_api::GuiDemoInteractiveServerMessage, ::mt4_term_api::GuiDemoInteractiveClientMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDemoOpenAccountInteractive(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DemoOpenAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DemoOpenAccount() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DemoOpenAccount(context, request, response); }));
    }
    ~WithRawCallbackMethod_DemoOpenAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DemoOpenAccount(::grpc::ServerContext* /*context*/, const ::mt4_term_api::GuiDemoOpenAccountRequest* /*request*/, ::mt4_term_api::GuiDemoOpenAccountReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DemoOpenAccount(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DemoOpenAccountInteractive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DemoOpenAccountInteractive() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->DemoOpenAccountInteractive(context); }));
    }
    ~WithRawCallbackMethod_DemoOpenAccountInteractive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DemoOpenAccountInteractive(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mt4_term_api::GuiDemoInteractiveServerMessage, ::mt4_term_api::GuiDemoInteractiveClientMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* DemoOpenAccountInteractive(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DemoOpenAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DemoOpenAccount() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mt4_term_api::GuiDemoOpenAccountRequest, ::mt4_term_api::GuiDemoOpenAccountReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mt4_term_api::GuiDemoOpenAccountRequest, ::mt4_term_api::GuiDemoOpenAccountReply>* streamer) {
                       return this->StreamedDemoOpenAccount(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DemoOpenAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DemoOpenAccount(::grpc::ServerContext* /*context*/, const ::mt4_term_api::GuiDemoOpenAccountRequest* /*request*/, ::mt4_term_api::GuiDemoOpenAccountReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDemoOpenAccount(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mt4_term_api::GuiDemoOpenAccountRequest,::mt4_term_api::GuiDemoOpenAccountReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_DemoOpenAccount<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_DemoOpenAccount<Service > StreamedService;
};

}  // namespace mt4_term_api


#endif  // GRPC_mt4_2dterm_2dapi_2dgui_2eproto__INCLUDED
