// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mt4-term-api-trading-helper.proto

#include "mt4-term-api-trading-helper.pb.h"
#include "mt4-term-api-trading-helper.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace mt4_term_api {

static const char* TradingHelper_method_names[] = {
  "/mt4_term_api.TradingHelper/OrderSend",
  "/mt4_term_api.TradingHelper/OrderModify",
  "/mt4_term_api.TradingHelper/OrderCloseDelete",
  "/mt4_term_api.TradingHelper/OrderCloseBy",
};

std::unique_ptr< TradingHelper::Stub> TradingHelper::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TradingHelper::Stub> stub(new TradingHelper::Stub(channel, options));
  return stub;
}

TradingHelper::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_OrderSend_(TradingHelper_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OrderModify_(TradingHelper_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OrderCloseDelete_(TradingHelper_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OrderCloseBy_(TradingHelper_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TradingHelper::Stub::OrderSend(::grpc::ClientContext* context, const ::mt4_term_api::OrderSendRequest& request, ::mt4_term_api::OrderSendReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt4_term_api::OrderSendRequest, ::mt4_term_api::OrderSendReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OrderSend_, context, request, response);
}

void TradingHelper::Stub::async::OrderSend(::grpc::ClientContext* context, const ::mt4_term_api::OrderSendRequest* request, ::mt4_term_api::OrderSendReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt4_term_api::OrderSendRequest, ::mt4_term_api::OrderSendReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OrderSend_, context, request, response, std::move(f));
}

void TradingHelper::Stub::async::OrderSend(::grpc::ClientContext* context, const ::mt4_term_api::OrderSendRequest* request, ::mt4_term_api::OrderSendReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OrderSend_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt4_term_api::OrderSendReply>* TradingHelper::Stub::PrepareAsyncOrderSendRaw(::grpc::ClientContext* context, const ::mt4_term_api::OrderSendRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt4_term_api::OrderSendReply, ::mt4_term_api::OrderSendRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OrderSend_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt4_term_api::OrderSendReply>* TradingHelper::Stub::AsyncOrderSendRaw(::grpc::ClientContext* context, const ::mt4_term_api::OrderSendRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOrderSendRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TradingHelper::Stub::OrderModify(::grpc::ClientContext* context, const ::mt4_term_api::OrderModifyRequest& request, ::mt4_term_api::OrderModifyReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt4_term_api::OrderModifyRequest, ::mt4_term_api::OrderModifyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OrderModify_, context, request, response);
}

void TradingHelper::Stub::async::OrderModify(::grpc::ClientContext* context, const ::mt4_term_api::OrderModifyRequest* request, ::mt4_term_api::OrderModifyReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt4_term_api::OrderModifyRequest, ::mt4_term_api::OrderModifyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OrderModify_, context, request, response, std::move(f));
}

void TradingHelper::Stub::async::OrderModify(::grpc::ClientContext* context, const ::mt4_term_api::OrderModifyRequest* request, ::mt4_term_api::OrderModifyReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OrderModify_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt4_term_api::OrderModifyReply>* TradingHelper::Stub::PrepareAsyncOrderModifyRaw(::grpc::ClientContext* context, const ::mt4_term_api::OrderModifyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt4_term_api::OrderModifyReply, ::mt4_term_api::OrderModifyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OrderModify_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt4_term_api::OrderModifyReply>* TradingHelper::Stub::AsyncOrderModifyRaw(::grpc::ClientContext* context, const ::mt4_term_api::OrderModifyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOrderModifyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TradingHelper::Stub::OrderCloseDelete(::grpc::ClientContext* context, const ::mt4_term_api::OrderCloseDeleteRequest& request, ::mt4_term_api::OrderCloseDeleteReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt4_term_api::OrderCloseDeleteRequest, ::mt4_term_api::OrderCloseDeleteReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OrderCloseDelete_, context, request, response);
}

void TradingHelper::Stub::async::OrderCloseDelete(::grpc::ClientContext* context, const ::mt4_term_api::OrderCloseDeleteRequest* request, ::mt4_term_api::OrderCloseDeleteReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt4_term_api::OrderCloseDeleteRequest, ::mt4_term_api::OrderCloseDeleteReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OrderCloseDelete_, context, request, response, std::move(f));
}

void TradingHelper::Stub::async::OrderCloseDelete(::grpc::ClientContext* context, const ::mt4_term_api::OrderCloseDeleteRequest* request, ::mt4_term_api::OrderCloseDeleteReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OrderCloseDelete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt4_term_api::OrderCloseDeleteReply>* TradingHelper::Stub::PrepareAsyncOrderCloseDeleteRaw(::grpc::ClientContext* context, const ::mt4_term_api::OrderCloseDeleteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt4_term_api::OrderCloseDeleteReply, ::mt4_term_api::OrderCloseDeleteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OrderCloseDelete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt4_term_api::OrderCloseDeleteReply>* TradingHelper::Stub::AsyncOrderCloseDeleteRaw(::grpc::ClientContext* context, const ::mt4_term_api::OrderCloseDeleteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOrderCloseDeleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TradingHelper::Stub::OrderCloseBy(::grpc::ClientContext* context, const ::mt4_term_api::OrderCloseByRequest& request, ::mt4_term_api::OrderCloseByReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt4_term_api::OrderCloseByRequest, ::mt4_term_api::OrderCloseByReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OrderCloseBy_, context, request, response);
}

void TradingHelper::Stub::async::OrderCloseBy(::grpc::ClientContext* context, const ::mt4_term_api::OrderCloseByRequest* request, ::mt4_term_api::OrderCloseByReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt4_term_api::OrderCloseByRequest, ::mt4_term_api::OrderCloseByReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OrderCloseBy_, context, request, response, std::move(f));
}

void TradingHelper::Stub::async::OrderCloseBy(::grpc::ClientContext* context, const ::mt4_term_api::OrderCloseByRequest* request, ::mt4_term_api::OrderCloseByReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OrderCloseBy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt4_term_api::OrderCloseByReply>* TradingHelper::Stub::PrepareAsyncOrderCloseByRaw(::grpc::ClientContext* context, const ::mt4_term_api::OrderCloseByRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt4_term_api::OrderCloseByReply, ::mt4_term_api::OrderCloseByRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OrderCloseBy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt4_term_api::OrderCloseByReply>* TradingHelper::Stub::AsyncOrderCloseByRaw(::grpc::ClientContext* context, const ::mt4_term_api::OrderCloseByRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOrderCloseByRaw(context, request, cq);
  result->StartCall();
  return result;
}

TradingHelper::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TradingHelper_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TradingHelper::Service, ::mt4_term_api::OrderSendRequest, ::mt4_term_api::OrderSendReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TradingHelper::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt4_term_api::OrderSendRequest* req,
             ::mt4_term_api::OrderSendReply* resp) {
               return service->OrderSend(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TradingHelper_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TradingHelper::Service, ::mt4_term_api::OrderModifyRequest, ::mt4_term_api::OrderModifyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TradingHelper::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt4_term_api::OrderModifyRequest* req,
             ::mt4_term_api::OrderModifyReply* resp) {
               return service->OrderModify(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TradingHelper_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TradingHelper::Service, ::mt4_term_api::OrderCloseDeleteRequest, ::mt4_term_api::OrderCloseDeleteReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TradingHelper::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt4_term_api::OrderCloseDeleteRequest* req,
             ::mt4_term_api::OrderCloseDeleteReply* resp) {
               return service->OrderCloseDelete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TradingHelper_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TradingHelper::Service, ::mt4_term_api::OrderCloseByRequest, ::mt4_term_api::OrderCloseByReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TradingHelper::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt4_term_api::OrderCloseByRequest* req,
             ::mt4_term_api::OrderCloseByReply* resp) {
               return service->OrderCloseBy(ctx, req, resp);
             }, this)));
}

TradingHelper::Service::~Service() {
}

::grpc::Status TradingHelper::Service::OrderSend(::grpc::ServerContext* context, const ::mt4_term_api::OrderSendRequest* request, ::mt4_term_api::OrderSendReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TradingHelper::Service::OrderModify(::grpc::ServerContext* context, const ::mt4_term_api::OrderModifyRequest* request, ::mt4_term_api::OrderModifyReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TradingHelper::Service::OrderCloseDelete(::grpc::ServerContext* context, const ::mt4_term_api::OrderCloseDeleteRequest* request, ::mt4_term_api::OrderCloseDeleteReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TradingHelper::Service::OrderCloseBy(::grpc::ServerContext* context, const ::mt4_term_api::OrderCloseByRequest* request, ::mt4_term_api::OrderCloseByReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mt4_term_api

