// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mt4-term-api-internal-charts.proto

#include "mt4-term-api-internal-charts.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace mt4_term_api {
PROTOBUF_CONSTEXPR CustomChartApplyTemplateReply::CustomChartApplyTemplateReply(
    ::_pbi::ConstantInitialized) {}
struct CustomChartApplyTemplateReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CustomChartApplyTemplateReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CustomChartApplyTemplateReplyDefaultTypeInternal() {}
  union {
    CustomChartApplyTemplateReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CustomChartApplyTemplateReplyDefaultTypeInternal _CustomChartApplyTemplateReply_default_instance_;
PROTOBUF_CONSTEXPR CustomChartApplyTemplateRequest::CustomChartApplyTemplateRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.template_file_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.chart_id_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CustomChartApplyTemplateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CustomChartApplyTemplateRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CustomChartApplyTemplateRequestDefaultTypeInternal() {}
  union {
    CustomChartApplyTemplateRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CustomChartApplyTemplateRequestDefaultTypeInternal _CustomChartApplyTemplateRequest_default_instance_;
PROTOBUF_CONSTEXPR CustomChartSaveTemplateRequest::CustomChartSaveTemplateRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.chart_id_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CustomChartSaveTemplateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CustomChartSaveTemplateRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CustomChartSaveTemplateRequestDefaultTypeInternal() {}
  union {
    CustomChartSaveTemplateRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CustomChartSaveTemplateRequestDefaultTypeInternal _CustomChartSaveTemplateRequest_default_instance_;
PROTOBUF_CONSTEXPR CustomChartSaveTemplateReply::CustomChartSaveTemplateReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.template_file_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CustomChartSaveTemplateReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CustomChartSaveTemplateReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CustomChartSaveTemplateReplyDefaultTypeInternal() {}
  union {
    CustomChartSaveTemplateReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CustomChartSaveTemplateReplyDefaultTypeInternal _CustomChartSaveTemplateReply_default_instance_;
PROTOBUF_CONSTEXPR CustomChartOpenRequest::CustomChartOpenRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.chart_symbol_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.chart_period_int_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CustomChartOpenRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CustomChartOpenRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CustomChartOpenRequestDefaultTypeInternal() {}
  union {
    CustomChartOpenRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CustomChartOpenRequestDefaultTypeInternal _CustomChartOpenRequest_default_instance_;
PROTOBUF_CONSTEXPR CustomChartOpenReply::CustomChartOpenReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.chart_id_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CustomChartOpenReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CustomChartOpenReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CustomChartOpenReplyDefaultTypeInternal() {}
  union {
    CustomChartOpenReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CustomChartOpenReplyDefaultTypeInternal _CustomChartOpenReply_default_instance_;
PROTOBUF_CONSTEXPR ChartOpenRequest::ChartOpenRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.chart_symbol_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.mode_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ChartOpenRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChartOpenRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChartOpenRequestDefaultTypeInternal() {}
  union {
    ChartOpenRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChartOpenRequestDefaultTypeInternal _ChartOpenRequest_default_instance_;
PROTOBUF_CONSTEXPR ChartOpenReply::ChartOpenReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.chart_terminal_id_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ChartOpenReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChartOpenReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChartOpenReplyDefaultTypeInternal() {}
  union {
    ChartOpenReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChartOpenReplyDefaultTypeInternal _ChartOpenReply_default_instance_;
PROTOBUF_CONSTEXPR ChartCloseRequest::ChartCloseRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.chart_terminal_id_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ChartCloseRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChartCloseRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChartCloseRequestDefaultTypeInternal() {}
  union {
    ChartCloseRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChartCloseRequestDefaultTypeInternal _ChartCloseRequest_default_instance_;
PROTOBUF_CONSTEXPR ChartCloseReply::ChartCloseReply(
    ::_pbi::ConstantInitialized) {}
struct ChartCloseReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChartCloseReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChartCloseReplyDefaultTypeInternal() {}
  union {
    ChartCloseReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChartCloseReplyDefaultTypeInternal _ChartCloseReply_default_instance_;
}  // namespace mt4_term_api
static ::_pb::Metadata file_level_metadata_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto[10];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto = nullptr;

const uint32_t TableStruct_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::CustomChartApplyTemplateReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::CustomChartApplyTemplateRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::CustomChartApplyTemplateRequest, _impl_.chart_id_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::CustomChartApplyTemplateRequest, _impl_.template_file_name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::CustomChartSaveTemplateRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::CustomChartSaveTemplateRequest, _impl_.chart_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::CustomChartSaveTemplateReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::CustomChartSaveTemplateReply, _impl_.template_file_name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::CustomChartOpenRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::CustomChartOpenRequest, _impl_.chart_symbol_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::CustomChartOpenRequest, _impl_.chart_period_int_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::CustomChartOpenReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::CustomChartOpenReply, _impl_.chart_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::ChartOpenRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::ChartOpenRequest, _impl_.chart_symbol_),
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::ChartOpenRequest, _impl_.mode_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::ChartOpenReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::ChartOpenReply, _impl_.chart_terminal_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::ChartCloseRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::ChartCloseRequest, _impl_.chart_terminal_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt4_term_api::ChartCloseReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::mt4_term_api::CustomChartApplyTemplateReply)},
  { 6, -1, -1, sizeof(::mt4_term_api::CustomChartApplyTemplateRequest)},
  { 14, -1, -1, sizeof(::mt4_term_api::CustomChartSaveTemplateRequest)},
  { 21, -1, -1, sizeof(::mt4_term_api::CustomChartSaveTemplateReply)},
  { 28, -1, -1, sizeof(::mt4_term_api::CustomChartOpenRequest)},
  { 36, -1, -1, sizeof(::mt4_term_api::CustomChartOpenReply)},
  { 43, -1, -1, sizeof(::mt4_term_api::ChartOpenRequest)},
  { 51, -1, -1, sizeof(::mt4_term_api::ChartOpenReply)},
  { 58, -1, -1, sizeof(::mt4_term_api::ChartCloseRequest)},
  { 65, -1, -1, sizeof(::mt4_term_api::ChartCloseReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::mt4_term_api::_CustomChartApplyTemplateReply_default_instance_._instance,
  &::mt4_term_api::_CustomChartApplyTemplateRequest_default_instance_._instance,
  &::mt4_term_api::_CustomChartSaveTemplateRequest_default_instance_._instance,
  &::mt4_term_api::_CustomChartSaveTemplateReply_default_instance_._instance,
  &::mt4_term_api::_CustomChartOpenRequest_default_instance_._instance,
  &::mt4_term_api::_CustomChartOpenReply_default_instance_._instance,
  &::mt4_term_api::_ChartOpenRequest_default_instance_._instance,
  &::mt4_term_api::_ChartOpenReply_default_instance_._instance,
  &::mt4_term_api::_ChartCloseRequest_default_instance_._instance,
  &::mt4_term_api::_ChartCloseReply_default_instance_._instance,
};

const char descriptor_table_protodef_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\"mt4-term-api-internal-charts.proto\022\014mt"
  "4_term_api\"\037\n\035CustomChartApplyTemplateRe"
  "ply\"O\n\037CustomChartApplyTemplateRequest\022\020"
  "\n\010chart_id\030\001 \001(\003\022\032\n\022template_file_name\030\002"
  " \001(\t\"2\n\036CustomChartSaveTemplateRequest\022\020"
  "\n\010chart_id\030\001 \001(\003\":\n\034CustomChartSaveTempl"
  "ateReply\022\032\n\022template_file_name\030\001 \001(\t\"H\n\026"
  "CustomChartOpenRequest\022\024\n\014chart_symbol\030\001"
  " \001(\t\022\030\n\020chart_period_int\030\002 \001(\005\"(\n\024Custom"
  "ChartOpenReply\022\020\n\010chart_id\030\001 \001(\003\"W\n\020Char"
  "tOpenRequest\022\024\n\014chart_symbol\030\001 \001(\t\022-\n\004mo"
  "de\030\002 \001(\0162\037.mt4_term_api.ChartTemplateMod"
  "e\"+\n\016ChartOpenReply\022\031\n\021chart_terminal_id"
  "\030\001 \001(\003\".\n\021ChartCloseRequest\022\031\n\021chart_ter"
  "minal_id\030\001 \001(\003\"\021\n\017ChartCloseReply*m\n\021Cha"
  "rtTemplateMode\022\014\n\010ON_TRADE\020\000\022\034\n\030ON_OPENE"
  "D_ORDERS_TICKETS\020\001\022\023\n\017ON_ORDER_PROFIT\020\002\022"
  "\027\n\023ON_SYMBOL_INFO_TICK\020\0032\363\003\n\016InternalCha"
  "rts\022I\n\tChartOpen\022\036.mt4_term_api.ChartOpe"
  "nRequest\032\034.mt4_term_api.ChartOpenReply\022L"
  "\n\nChartClose\022\037.mt4_term_api.ChartCloseRe"
  "quest\032\035.mt4_term_api.ChartCloseReply\022[\n\017"
  "CustomChartOpen\022$.mt4_term_api.CustomCha"
  "rtOpenRequest\032\".mt4_term_api.CustomChart"
  "OpenReply\022s\n\027CustomChartSaveTemplate\022,.m"
  "t4_term_api.CustomChartSaveTemplateReque"
  "st\032*.mt4_term_api.CustomChartSaveTemplat"
  "eReply\022v\n\030CustomChartApplyTemplate\022-.mt4"
  "_term_api.CustomChartApplyTemplateReques"
  "t\032+.mt4_term_api.CustomChartApplyTemplat"
  "eReplyBBZ1git.mtapi.io/root/mrpc-proto.g"
  "it/mt4/libraries/go\252\002\014mt4_term_apib\006prot"
  "o3"
  ;
static ::_pbi::once_flag descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto = {
    false, false, 1282, descriptor_table_protodef_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto,
    "mt4-term-api-internal-charts.proto",
    &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_once, nullptr, 0, 10,
    schemas, file_default_instances, TableStruct_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto::offsets,
    file_level_metadata_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto, file_level_enum_descriptors_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto,
    file_level_service_descriptors_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_getter() {
  return &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto(&descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto);
namespace mt4_term_api {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ChartTemplateMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto);
  return file_level_enum_descriptors_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto[0];
}
bool ChartTemplateMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class CustomChartApplyTemplateReply::_Internal {
 public:
};

CustomChartApplyTemplateReply::CustomChartApplyTemplateReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:mt4_term_api.CustomChartApplyTemplateReply)
}
CustomChartApplyTemplateReply::CustomChartApplyTemplateReply(const CustomChartApplyTemplateReply& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  CustomChartApplyTemplateReply* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mt4_term_api.CustomChartApplyTemplateReply)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CustomChartApplyTemplateReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CustomChartApplyTemplateReply::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata CustomChartApplyTemplateReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_getter, &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_once,
      file_level_metadata_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto[0]);
}

// ===================================================================

class CustomChartApplyTemplateRequest::_Internal {
 public:
};

CustomChartApplyTemplateRequest::CustomChartApplyTemplateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mt4_term_api.CustomChartApplyTemplateRequest)
}
CustomChartApplyTemplateRequest::CustomChartApplyTemplateRequest(const CustomChartApplyTemplateRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CustomChartApplyTemplateRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.template_file_name_){}
    , decltype(_impl_.chart_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.template_file_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.template_file_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_template_file_name().empty()) {
    _this->_impl_.template_file_name_.Set(from._internal_template_file_name(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.chart_id_ = from._impl_.chart_id_;
  // @@protoc_insertion_point(copy_constructor:mt4_term_api.CustomChartApplyTemplateRequest)
}

inline void CustomChartApplyTemplateRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.template_file_name_){}
    , decltype(_impl_.chart_id_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.template_file_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.template_file_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CustomChartApplyTemplateRequest::~CustomChartApplyTemplateRequest() {
  // @@protoc_insertion_point(destructor:mt4_term_api.CustomChartApplyTemplateRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CustomChartApplyTemplateRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.template_file_name_.Destroy();
}

void CustomChartApplyTemplateRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CustomChartApplyTemplateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mt4_term_api.CustomChartApplyTemplateRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.template_file_name_.ClearToEmpty();
  _impl_.chart_id_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CustomChartApplyTemplateRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 chart_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.chart_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string template_file_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_template_file_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt4_term_api.CustomChartApplyTemplateRequest.template_file_name"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CustomChartApplyTemplateRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mt4_term_api.CustomChartApplyTemplateRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 chart_id = 1;
  if (this->_internal_chart_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_chart_id(), target);
  }

  // string template_file_name = 2;
  if (!this->_internal_template_file_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_template_file_name().data(), static_cast<int>(this->_internal_template_file_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt4_term_api.CustomChartApplyTemplateRequest.template_file_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_template_file_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mt4_term_api.CustomChartApplyTemplateRequest)
  return target;
}

size_t CustomChartApplyTemplateRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mt4_term_api.CustomChartApplyTemplateRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string template_file_name = 2;
  if (!this->_internal_template_file_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_template_file_name());
  }

  // int64 chart_id = 1;
  if (this->_internal_chart_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_chart_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CustomChartApplyTemplateRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CustomChartApplyTemplateRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CustomChartApplyTemplateRequest::GetClassData() const { return &_class_data_; }


void CustomChartApplyTemplateRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CustomChartApplyTemplateRequest*>(&to_msg);
  auto& from = static_cast<const CustomChartApplyTemplateRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mt4_term_api.CustomChartApplyTemplateRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_template_file_name().empty()) {
    _this->_internal_set_template_file_name(from._internal_template_file_name());
  }
  if (from._internal_chart_id() != 0) {
    _this->_internal_set_chart_id(from._internal_chart_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CustomChartApplyTemplateRequest::CopyFrom(const CustomChartApplyTemplateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mt4_term_api.CustomChartApplyTemplateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CustomChartApplyTemplateRequest::IsInitialized() const {
  return true;
}

void CustomChartApplyTemplateRequest::InternalSwap(CustomChartApplyTemplateRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.template_file_name_, lhs_arena,
      &other->_impl_.template_file_name_, rhs_arena
  );
  swap(_impl_.chart_id_, other->_impl_.chart_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CustomChartApplyTemplateRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_getter, &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_once,
      file_level_metadata_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto[1]);
}

// ===================================================================

class CustomChartSaveTemplateRequest::_Internal {
 public:
};

CustomChartSaveTemplateRequest::CustomChartSaveTemplateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mt4_term_api.CustomChartSaveTemplateRequest)
}
CustomChartSaveTemplateRequest::CustomChartSaveTemplateRequest(const CustomChartSaveTemplateRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CustomChartSaveTemplateRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.chart_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.chart_id_ = from._impl_.chart_id_;
  // @@protoc_insertion_point(copy_constructor:mt4_term_api.CustomChartSaveTemplateRequest)
}

inline void CustomChartSaveTemplateRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.chart_id_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CustomChartSaveTemplateRequest::~CustomChartSaveTemplateRequest() {
  // @@protoc_insertion_point(destructor:mt4_term_api.CustomChartSaveTemplateRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CustomChartSaveTemplateRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CustomChartSaveTemplateRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CustomChartSaveTemplateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mt4_term_api.CustomChartSaveTemplateRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.chart_id_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CustomChartSaveTemplateRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 chart_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.chart_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CustomChartSaveTemplateRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mt4_term_api.CustomChartSaveTemplateRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 chart_id = 1;
  if (this->_internal_chart_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_chart_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mt4_term_api.CustomChartSaveTemplateRequest)
  return target;
}

size_t CustomChartSaveTemplateRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mt4_term_api.CustomChartSaveTemplateRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 chart_id = 1;
  if (this->_internal_chart_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_chart_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CustomChartSaveTemplateRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CustomChartSaveTemplateRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CustomChartSaveTemplateRequest::GetClassData() const { return &_class_data_; }


void CustomChartSaveTemplateRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CustomChartSaveTemplateRequest*>(&to_msg);
  auto& from = static_cast<const CustomChartSaveTemplateRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mt4_term_api.CustomChartSaveTemplateRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_chart_id() != 0) {
    _this->_internal_set_chart_id(from._internal_chart_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CustomChartSaveTemplateRequest::CopyFrom(const CustomChartSaveTemplateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mt4_term_api.CustomChartSaveTemplateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CustomChartSaveTemplateRequest::IsInitialized() const {
  return true;
}

void CustomChartSaveTemplateRequest::InternalSwap(CustomChartSaveTemplateRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.chart_id_, other->_impl_.chart_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CustomChartSaveTemplateRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_getter, &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_once,
      file_level_metadata_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto[2]);
}

// ===================================================================

class CustomChartSaveTemplateReply::_Internal {
 public:
};

CustomChartSaveTemplateReply::CustomChartSaveTemplateReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mt4_term_api.CustomChartSaveTemplateReply)
}
CustomChartSaveTemplateReply::CustomChartSaveTemplateReply(const CustomChartSaveTemplateReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CustomChartSaveTemplateReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.template_file_name_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.template_file_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.template_file_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_template_file_name().empty()) {
    _this->_impl_.template_file_name_.Set(from._internal_template_file_name(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:mt4_term_api.CustomChartSaveTemplateReply)
}

inline void CustomChartSaveTemplateReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.template_file_name_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.template_file_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.template_file_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CustomChartSaveTemplateReply::~CustomChartSaveTemplateReply() {
  // @@protoc_insertion_point(destructor:mt4_term_api.CustomChartSaveTemplateReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CustomChartSaveTemplateReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.template_file_name_.Destroy();
}

void CustomChartSaveTemplateReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CustomChartSaveTemplateReply::Clear() {
// @@protoc_insertion_point(message_clear_start:mt4_term_api.CustomChartSaveTemplateReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.template_file_name_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CustomChartSaveTemplateReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string template_file_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_template_file_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt4_term_api.CustomChartSaveTemplateReply.template_file_name"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CustomChartSaveTemplateReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mt4_term_api.CustomChartSaveTemplateReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string template_file_name = 1;
  if (!this->_internal_template_file_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_template_file_name().data(), static_cast<int>(this->_internal_template_file_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt4_term_api.CustomChartSaveTemplateReply.template_file_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_template_file_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mt4_term_api.CustomChartSaveTemplateReply)
  return target;
}

size_t CustomChartSaveTemplateReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mt4_term_api.CustomChartSaveTemplateReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string template_file_name = 1;
  if (!this->_internal_template_file_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_template_file_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CustomChartSaveTemplateReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CustomChartSaveTemplateReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CustomChartSaveTemplateReply::GetClassData() const { return &_class_data_; }


void CustomChartSaveTemplateReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CustomChartSaveTemplateReply*>(&to_msg);
  auto& from = static_cast<const CustomChartSaveTemplateReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mt4_term_api.CustomChartSaveTemplateReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_template_file_name().empty()) {
    _this->_internal_set_template_file_name(from._internal_template_file_name());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CustomChartSaveTemplateReply::CopyFrom(const CustomChartSaveTemplateReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mt4_term_api.CustomChartSaveTemplateReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CustomChartSaveTemplateReply::IsInitialized() const {
  return true;
}

void CustomChartSaveTemplateReply::InternalSwap(CustomChartSaveTemplateReply* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.template_file_name_, lhs_arena,
      &other->_impl_.template_file_name_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata CustomChartSaveTemplateReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_getter, &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_once,
      file_level_metadata_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto[3]);
}

// ===================================================================

class CustomChartOpenRequest::_Internal {
 public:
};

CustomChartOpenRequest::CustomChartOpenRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mt4_term_api.CustomChartOpenRequest)
}
CustomChartOpenRequest::CustomChartOpenRequest(const CustomChartOpenRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CustomChartOpenRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.chart_symbol_){}
    , decltype(_impl_.chart_period_int_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.chart_symbol_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.chart_symbol_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_chart_symbol().empty()) {
    _this->_impl_.chart_symbol_.Set(from._internal_chart_symbol(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.chart_period_int_ = from._impl_.chart_period_int_;
  // @@protoc_insertion_point(copy_constructor:mt4_term_api.CustomChartOpenRequest)
}

inline void CustomChartOpenRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.chart_symbol_){}
    , decltype(_impl_.chart_period_int_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.chart_symbol_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.chart_symbol_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CustomChartOpenRequest::~CustomChartOpenRequest() {
  // @@protoc_insertion_point(destructor:mt4_term_api.CustomChartOpenRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CustomChartOpenRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.chart_symbol_.Destroy();
}

void CustomChartOpenRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CustomChartOpenRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mt4_term_api.CustomChartOpenRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.chart_symbol_.ClearToEmpty();
  _impl_.chart_period_int_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CustomChartOpenRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string chart_symbol = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_chart_symbol();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt4_term_api.CustomChartOpenRequest.chart_symbol"));
        } else
          goto handle_unusual;
        continue;
      // int32 chart_period_int = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.chart_period_int_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CustomChartOpenRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mt4_term_api.CustomChartOpenRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string chart_symbol = 1;
  if (!this->_internal_chart_symbol().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_chart_symbol().data(), static_cast<int>(this->_internal_chart_symbol().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt4_term_api.CustomChartOpenRequest.chart_symbol");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_chart_symbol(), target);
  }

  // int32 chart_period_int = 2;
  if (this->_internal_chart_period_int() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_chart_period_int(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mt4_term_api.CustomChartOpenRequest)
  return target;
}

size_t CustomChartOpenRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mt4_term_api.CustomChartOpenRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string chart_symbol = 1;
  if (!this->_internal_chart_symbol().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_chart_symbol());
  }

  // int32 chart_period_int = 2;
  if (this->_internal_chart_period_int() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_chart_period_int());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CustomChartOpenRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CustomChartOpenRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CustomChartOpenRequest::GetClassData() const { return &_class_data_; }


void CustomChartOpenRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CustomChartOpenRequest*>(&to_msg);
  auto& from = static_cast<const CustomChartOpenRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mt4_term_api.CustomChartOpenRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_chart_symbol().empty()) {
    _this->_internal_set_chart_symbol(from._internal_chart_symbol());
  }
  if (from._internal_chart_period_int() != 0) {
    _this->_internal_set_chart_period_int(from._internal_chart_period_int());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CustomChartOpenRequest::CopyFrom(const CustomChartOpenRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mt4_term_api.CustomChartOpenRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CustomChartOpenRequest::IsInitialized() const {
  return true;
}

void CustomChartOpenRequest::InternalSwap(CustomChartOpenRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.chart_symbol_, lhs_arena,
      &other->_impl_.chart_symbol_, rhs_arena
  );
  swap(_impl_.chart_period_int_, other->_impl_.chart_period_int_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CustomChartOpenRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_getter, &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_once,
      file_level_metadata_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto[4]);
}

// ===================================================================

class CustomChartOpenReply::_Internal {
 public:
};

CustomChartOpenReply::CustomChartOpenReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mt4_term_api.CustomChartOpenReply)
}
CustomChartOpenReply::CustomChartOpenReply(const CustomChartOpenReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CustomChartOpenReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.chart_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.chart_id_ = from._impl_.chart_id_;
  // @@protoc_insertion_point(copy_constructor:mt4_term_api.CustomChartOpenReply)
}

inline void CustomChartOpenReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.chart_id_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CustomChartOpenReply::~CustomChartOpenReply() {
  // @@protoc_insertion_point(destructor:mt4_term_api.CustomChartOpenReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CustomChartOpenReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CustomChartOpenReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CustomChartOpenReply::Clear() {
// @@protoc_insertion_point(message_clear_start:mt4_term_api.CustomChartOpenReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.chart_id_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CustomChartOpenReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 chart_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.chart_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CustomChartOpenReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mt4_term_api.CustomChartOpenReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 chart_id = 1;
  if (this->_internal_chart_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_chart_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mt4_term_api.CustomChartOpenReply)
  return target;
}

size_t CustomChartOpenReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mt4_term_api.CustomChartOpenReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 chart_id = 1;
  if (this->_internal_chart_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_chart_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CustomChartOpenReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CustomChartOpenReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CustomChartOpenReply::GetClassData() const { return &_class_data_; }


void CustomChartOpenReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CustomChartOpenReply*>(&to_msg);
  auto& from = static_cast<const CustomChartOpenReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mt4_term_api.CustomChartOpenReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_chart_id() != 0) {
    _this->_internal_set_chart_id(from._internal_chart_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CustomChartOpenReply::CopyFrom(const CustomChartOpenReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mt4_term_api.CustomChartOpenReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CustomChartOpenReply::IsInitialized() const {
  return true;
}

void CustomChartOpenReply::InternalSwap(CustomChartOpenReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.chart_id_, other->_impl_.chart_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CustomChartOpenReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_getter, &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_once,
      file_level_metadata_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto[5]);
}

// ===================================================================

class ChartOpenRequest::_Internal {
 public:
};

ChartOpenRequest::ChartOpenRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mt4_term_api.ChartOpenRequest)
}
ChartOpenRequest::ChartOpenRequest(const ChartOpenRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ChartOpenRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.chart_symbol_){}
    , decltype(_impl_.mode_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.chart_symbol_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.chart_symbol_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_chart_symbol().empty()) {
    _this->_impl_.chart_symbol_.Set(from._internal_chart_symbol(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.mode_ = from._impl_.mode_;
  // @@protoc_insertion_point(copy_constructor:mt4_term_api.ChartOpenRequest)
}

inline void ChartOpenRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.chart_symbol_){}
    , decltype(_impl_.mode_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.chart_symbol_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.chart_symbol_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ChartOpenRequest::~ChartOpenRequest() {
  // @@protoc_insertion_point(destructor:mt4_term_api.ChartOpenRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ChartOpenRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.chart_symbol_.Destroy();
}

void ChartOpenRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ChartOpenRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mt4_term_api.ChartOpenRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.chart_symbol_.ClearToEmpty();
  _impl_.mode_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ChartOpenRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string chart_symbol = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_chart_symbol();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt4_term_api.ChartOpenRequest.chart_symbol"));
        } else
          goto handle_unusual;
        continue;
      // .mt4_term_api.ChartTemplateMode mode = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_mode(static_cast<::mt4_term_api::ChartTemplateMode>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ChartOpenRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mt4_term_api.ChartOpenRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string chart_symbol = 1;
  if (!this->_internal_chart_symbol().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_chart_symbol().data(), static_cast<int>(this->_internal_chart_symbol().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt4_term_api.ChartOpenRequest.chart_symbol");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_chart_symbol(), target);
  }

  // .mt4_term_api.ChartTemplateMode mode = 2;
  if (this->_internal_mode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_mode(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mt4_term_api.ChartOpenRequest)
  return target;
}

size_t ChartOpenRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mt4_term_api.ChartOpenRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string chart_symbol = 1;
  if (!this->_internal_chart_symbol().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_chart_symbol());
  }

  // .mt4_term_api.ChartTemplateMode mode = 2;
  if (this->_internal_mode() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_mode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ChartOpenRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ChartOpenRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ChartOpenRequest::GetClassData() const { return &_class_data_; }


void ChartOpenRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ChartOpenRequest*>(&to_msg);
  auto& from = static_cast<const ChartOpenRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mt4_term_api.ChartOpenRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_chart_symbol().empty()) {
    _this->_internal_set_chart_symbol(from._internal_chart_symbol());
  }
  if (from._internal_mode() != 0) {
    _this->_internal_set_mode(from._internal_mode());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ChartOpenRequest::CopyFrom(const ChartOpenRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mt4_term_api.ChartOpenRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChartOpenRequest::IsInitialized() const {
  return true;
}

void ChartOpenRequest::InternalSwap(ChartOpenRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.chart_symbol_, lhs_arena,
      &other->_impl_.chart_symbol_, rhs_arena
  );
  swap(_impl_.mode_, other->_impl_.mode_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ChartOpenRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_getter, &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_once,
      file_level_metadata_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto[6]);
}

// ===================================================================

class ChartOpenReply::_Internal {
 public:
};

ChartOpenReply::ChartOpenReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mt4_term_api.ChartOpenReply)
}
ChartOpenReply::ChartOpenReply(const ChartOpenReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ChartOpenReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.chart_terminal_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.chart_terminal_id_ = from._impl_.chart_terminal_id_;
  // @@protoc_insertion_point(copy_constructor:mt4_term_api.ChartOpenReply)
}

inline void ChartOpenReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.chart_terminal_id_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ChartOpenReply::~ChartOpenReply() {
  // @@protoc_insertion_point(destructor:mt4_term_api.ChartOpenReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ChartOpenReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ChartOpenReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ChartOpenReply::Clear() {
// @@protoc_insertion_point(message_clear_start:mt4_term_api.ChartOpenReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.chart_terminal_id_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ChartOpenReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 chart_terminal_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.chart_terminal_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ChartOpenReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mt4_term_api.ChartOpenReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 chart_terminal_id = 1;
  if (this->_internal_chart_terminal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_chart_terminal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mt4_term_api.ChartOpenReply)
  return target;
}

size_t ChartOpenReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mt4_term_api.ChartOpenReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 chart_terminal_id = 1;
  if (this->_internal_chart_terminal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_chart_terminal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ChartOpenReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ChartOpenReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ChartOpenReply::GetClassData() const { return &_class_data_; }


void ChartOpenReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ChartOpenReply*>(&to_msg);
  auto& from = static_cast<const ChartOpenReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mt4_term_api.ChartOpenReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_chart_terminal_id() != 0) {
    _this->_internal_set_chart_terminal_id(from._internal_chart_terminal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ChartOpenReply::CopyFrom(const ChartOpenReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mt4_term_api.ChartOpenReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChartOpenReply::IsInitialized() const {
  return true;
}

void ChartOpenReply::InternalSwap(ChartOpenReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.chart_terminal_id_, other->_impl_.chart_terminal_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ChartOpenReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_getter, &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_once,
      file_level_metadata_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto[7]);
}

// ===================================================================

class ChartCloseRequest::_Internal {
 public:
};

ChartCloseRequest::ChartCloseRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mt4_term_api.ChartCloseRequest)
}
ChartCloseRequest::ChartCloseRequest(const ChartCloseRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ChartCloseRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.chart_terminal_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.chart_terminal_id_ = from._impl_.chart_terminal_id_;
  // @@protoc_insertion_point(copy_constructor:mt4_term_api.ChartCloseRequest)
}

inline void ChartCloseRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.chart_terminal_id_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ChartCloseRequest::~ChartCloseRequest() {
  // @@protoc_insertion_point(destructor:mt4_term_api.ChartCloseRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ChartCloseRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ChartCloseRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ChartCloseRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mt4_term_api.ChartCloseRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.chart_terminal_id_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ChartCloseRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 chart_terminal_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.chart_terminal_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ChartCloseRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mt4_term_api.ChartCloseRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 chart_terminal_id = 1;
  if (this->_internal_chart_terminal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_chart_terminal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mt4_term_api.ChartCloseRequest)
  return target;
}

size_t ChartCloseRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mt4_term_api.ChartCloseRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 chart_terminal_id = 1;
  if (this->_internal_chart_terminal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_chart_terminal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ChartCloseRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ChartCloseRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ChartCloseRequest::GetClassData() const { return &_class_data_; }


void ChartCloseRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ChartCloseRequest*>(&to_msg);
  auto& from = static_cast<const ChartCloseRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mt4_term_api.ChartCloseRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_chart_terminal_id() != 0) {
    _this->_internal_set_chart_terminal_id(from._internal_chart_terminal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ChartCloseRequest::CopyFrom(const ChartCloseRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mt4_term_api.ChartCloseRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChartCloseRequest::IsInitialized() const {
  return true;
}

void ChartCloseRequest::InternalSwap(ChartCloseRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.chart_terminal_id_, other->_impl_.chart_terminal_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ChartCloseRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_getter, &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_once,
      file_level_metadata_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto[8]);
}

// ===================================================================

class ChartCloseReply::_Internal {
 public:
};

ChartCloseReply::ChartCloseReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:mt4_term_api.ChartCloseReply)
}
ChartCloseReply::ChartCloseReply(const ChartCloseReply& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  ChartCloseReply* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mt4_term_api.ChartCloseReply)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ChartCloseReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ChartCloseReply::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ChartCloseReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_getter, &descriptor_table_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto_once,
      file_level_metadata_mt4_2dterm_2dapi_2dinternal_2dcharts_2eproto[9]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace mt4_term_api
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mt4_term_api::CustomChartApplyTemplateReply*
Arena::CreateMaybeMessage< ::mt4_term_api::CustomChartApplyTemplateReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt4_term_api::CustomChartApplyTemplateReply >(arena);
}
template<> PROTOBUF_NOINLINE ::mt4_term_api::CustomChartApplyTemplateRequest*
Arena::CreateMaybeMessage< ::mt4_term_api::CustomChartApplyTemplateRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt4_term_api::CustomChartApplyTemplateRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mt4_term_api::CustomChartSaveTemplateRequest*
Arena::CreateMaybeMessage< ::mt4_term_api::CustomChartSaveTemplateRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt4_term_api::CustomChartSaveTemplateRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mt4_term_api::CustomChartSaveTemplateReply*
Arena::CreateMaybeMessage< ::mt4_term_api::CustomChartSaveTemplateReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt4_term_api::CustomChartSaveTemplateReply >(arena);
}
template<> PROTOBUF_NOINLINE ::mt4_term_api::CustomChartOpenRequest*
Arena::CreateMaybeMessage< ::mt4_term_api::CustomChartOpenRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt4_term_api::CustomChartOpenRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mt4_term_api::CustomChartOpenReply*
Arena::CreateMaybeMessage< ::mt4_term_api::CustomChartOpenReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt4_term_api::CustomChartOpenReply >(arena);
}
template<> PROTOBUF_NOINLINE ::mt4_term_api::ChartOpenRequest*
Arena::CreateMaybeMessage< ::mt4_term_api::ChartOpenRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt4_term_api::ChartOpenRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mt4_term_api::ChartOpenReply*
Arena::CreateMaybeMessage< ::mt4_term_api::ChartOpenReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt4_term_api::ChartOpenReply >(arena);
}
template<> PROTOBUF_NOINLINE ::mt4_term_api::ChartCloseRequest*
Arena::CreateMaybeMessage< ::mt4_term_api::ChartCloseRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt4_term_api::ChartCloseRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mt4_term_api::ChartCloseReply*
Arena::CreateMaybeMessage< ::mt4_term_api::ChartCloseReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt4_term_api::ChartCloseReply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
